-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tiny_ecg_inference_relu_i8 is
port (
    ap_ready : OUT STD_LOGIC;
    value_r : IN STD_LOGIC_VECTOR (20 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (6 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of tiny_ecg_inference_relu_i8 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal tmp_11_fu_34_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_fu_26_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln11_fu_54_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln5_fu_44_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln11_fu_68_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln11_1_fu_60_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln7_fu_50_p1 : STD_LOGIC_VECTOR (6 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= 
        select_ln11_1_fu_60_p3 when (or_ln11_fu_68_p2(0) = '1') else 
        trunc_ln7_fu_50_p1;
    icmp_ln5_fu_44_p2 <= "1" when (signed(tmp_11_fu_34_p4) > signed(ap_const_lv14_0)) else "0";
    or_ln11_fu_68_p2 <= (tmp_fu_26_p3 or icmp_ln5_fu_44_p2);
    select_ln11_1_fu_60_p3 <= 
        ap_const_lv7_7F when (xor_ln11_fu_54_p2(0) = '1') else 
        ap_const_lv7_0;
    tmp_11_fu_34_p4 <= value_r(20 downto 7);
    tmp_fu_26_p3 <= value_r(20 downto 20);
    trunc_ln7_fu_50_p1 <= value_r(7 - 1 downto 0);
    xor_ln11_fu_54_p2 <= (tmp_fu_26_p3 xor ap_const_lv1_1);
end behav;
