-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_116_12_VITIS_LOOP_117_13 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    buffer_c3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_c3_ce0 : OUT STD_LOGIC;
    buffer_c3_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
    buffer_c3_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_c3_1_ce0 : OUT STD_LOGIC;
    buffer_c3_1_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
    buffer_c3_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_c3_2_ce0 : OUT STD_LOGIC;
    buffer_c3_2_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
    buffer_c3_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_c3_3_ce0 : OUT STD_LOGIC;
    buffer_c3_3_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
    buffer_c3_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_c3_4_ce0 : OUT STD_LOGIC;
    buffer_c3_4_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
    buffer_c3_5_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_c3_5_ce0 : OUT STD_LOGIC;
    buffer_c3_5_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
    buffer_c3_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_c3_6_ce0 : OUT STD_LOGIC;
    buffer_c3_6_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
    buffer_c3_7_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_c3_7_ce0 : OUT STD_LOGIC;
    buffer_c3_7_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
    buffer_c3_8_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_c3_8_ce0 : OUT STD_LOGIC;
    buffer_c3_8_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
    buffer_c3_9_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_c3_9_ce0 : OUT STD_LOGIC;
    buffer_c3_9_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
    buffer_c3_10_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_c3_10_ce0 : OUT STD_LOGIC;
    buffer_c3_10_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
    buffer_c3_11_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_c3_11_ce0 : OUT STD_LOGIC;
    buffer_c3_11_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
    flatten_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    flatten_ce0 : OUT STD_LOGIC;
    flatten_we0 : OUT STD_LOGIC;
    flatten_d0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
end;


architecture behav of tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_116_12_VITIS_LOOP_117_13 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_C0 : STD_LOGIC_VECTOR (7 downto 0) := "11000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln116_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln116_fu_320_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln116_reg_498 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln119_fu_392_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln119_reg_563 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln119_reg_563_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_414_p27 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_s_reg_568 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln116_fu_342_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln119_1_fu_469_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_92 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln117_fu_398_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_96 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln116_1_fu_336_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten_fu_100 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln116_fu_297_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_c3_ce0_local : STD_LOGIC;
    signal buffer_c3_1_ce0_local : STD_LOGIC;
    signal buffer_c3_2_ce0_local : STD_LOGIC;
    signal buffer_c3_3_ce0_local : STD_LOGIC;
    signal buffer_c3_4_ce0_local : STD_LOGIC;
    signal buffer_c3_5_ce0_local : STD_LOGIC;
    signal buffer_c3_6_ce0_local : STD_LOGIC;
    signal buffer_c3_7_ce0_local : STD_LOGIC;
    signal buffer_c3_8_ce0_local : STD_LOGIC;
    signal buffer_c3_9_ce0_local : STD_LOGIC;
    signal buffer_c3_10_ce0_local : STD_LOGIC;
    signal buffer_c3_11_ce0_local : STD_LOGIC;
    signal flatten_we0_local : STD_LOGIC;
    signal flatten_ce0_local : STD_LOGIC;
    signal icmp_ln117_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_328_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln119_fu_358_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_370_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl_fu_362_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln119_fu_378_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln117_fu_388_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln119_fu_382_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_414_p25 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_s_fu_414_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_414_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_414_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_414_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_414_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_414_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_414_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_414_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_414_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_414_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_414_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_414_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component tiny_ecg_inference_sparsemux_25_4_7_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (6 downto 0);
        din3 : IN STD_LOGIC_VECTOR (6 downto 0);
        din4 : IN STD_LOGIC_VECTOR (6 downto 0);
        din5 : IN STD_LOGIC_VECTOR (6 downto 0);
        din6 : IN STD_LOGIC_VECTOR (6 downto 0);
        din7 : IN STD_LOGIC_VECTOR (6 downto 0);
        din8 : IN STD_LOGIC_VECTOR (6 downto 0);
        din9 : IN STD_LOGIC_VECTOR (6 downto 0);
        din10 : IN STD_LOGIC_VECTOR (6 downto 0);
        din11 : IN STD_LOGIC_VECTOR (6 downto 0);
        def : IN STD_LOGIC_VECTOR (6 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component tiny_ecg_inference_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_25_4_7_1_1_U3272 : component tiny_ecg_inference_sparsemux_25_4_7_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 7,
        CASE1 => "0001",
        din1_WIDTH => 7,
        CASE2 => "0010",
        din2_WIDTH => 7,
        CASE3 => "0011",
        din3_WIDTH => 7,
        CASE4 => "0100",
        din4_WIDTH => 7,
        CASE5 => "0101",
        din5_WIDTH => 7,
        CASE6 => "0110",
        din6_WIDTH => 7,
        CASE7 => "0111",
        din7_WIDTH => 7,
        CASE8 => "1000",
        din8_WIDTH => 7,
        CASE9 => "1001",
        din9_WIDTH => 7,
        CASE10 => "1010",
        din10_WIDTH => 7,
        CASE11 => "1011",
        din11_WIDTH => 7,
        def_WIDTH => 7,
        sel_WIDTH => 4,
        dout_WIDTH => 7)
    port map (
        din0 => buffer_c3_q0,
        din1 => buffer_c3_1_q0,
        din2 => buffer_c3_2_q0,
        din3 => buffer_c3_3_q0,
        din4 => buffer_c3_4_q0,
        din5 => buffer_c3_5_q0,
        din6 => buffer_c3_6_q0,
        din7 => buffer_c3_7_q0,
        din8 => buffer_c3_8_q0,
        din9 => buffer_c3_9_q0,
        din10 => buffer_c3_10_q0,
        din11 => buffer_c3_11_q0,
        def => tmp_s_fu_414_p25,
        sel => select_ln116_reg_498,
        dout => tmp_s_fu_414_p27);

    flow_control_loop_pipe_sequential_init_U : component tiny_ecg_inference_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    i_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_96 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_fu_96 <= add_ln116_1_fu_336_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln116_fu_291_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_100 <= add_ln116_fu_297_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_100 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_92 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_fu_92 <= add_ln117_fu_398_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln119_reg_563 <= add_ln119_fu_392_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                select_ln116_reg_498 <= select_ln116_fu_320_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln119_reg_563_pp0_iter2_reg <= add_ln119_reg_563;
                tmp_s_reg_568 <= tmp_s_fu_414_p27;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln116_1_fu_336_p2 <= std_logic_vector(unsigned(i_fu_96) + unsigned(empty_fu_328_p3));
    add_ln116_fu_297_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv8_1));
    add_ln117_fu_398_p2 <= std_logic_vector(unsigned(select_ln116_fu_320_p3) + unsigned(ap_const_lv4_1));
    add_ln119_fu_392_p2 <= std_logic_vector(unsigned(zext_ln117_fu_388_p1) + unsigned(sub_ln119_fu_382_p2));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln116_fu_291_p2)
    begin
        if (((icmp_ln116_fu_291_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_100)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_100;
        end if; 
    end process;

    buffer_c3_10_address0 <= zext_ln116_fu_342_p1(4 - 1 downto 0);
    buffer_c3_10_ce0 <= buffer_c3_10_ce0_local;

    buffer_c3_10_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_c3_10_ce0_local <= ap_const_logic_1;
        else 
            buffer_c3_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_c3_11_address0 <= zext_ln116_fu_342_p1(4 - 1 downto 0);
    buffer_c3_11_ce0 <= buffer_c3_11_ce0_local;

    buffer_c3_11_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_c3_11_ce0_local <= ap_const_logic_1;
        else 
            buffer_c3_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_c3_1_address0 <= zext_ln116_fu_342_p1(4 - 1 downto 0);
    buffer_c3_1_ce0 <= buffer_c3_1_ce0_local;

    buffer_c3_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_c3_1_ce0_local <= ap_const_logic_1;
        else 
            buffer_c3_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_c3_2_address0 <= zext_ln116_fu_342_p1(4 - 1 downto 0);
    buffer_c3_2_ce0 <= buffer_c3_2_ce0_local;

    buffer_c3_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_c3_2_ce0_local <= ap_const_logic_1;
        else 
            buffer_c3_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_c3_3_address0 <= zext_ln116_fu_342_p1(4 - 1 downto 0);
    buffer_c3_3_ce0 <= buffer_c3_3_ce0_local;

    buffer_c3_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_c3_3_ce0_local <= ap_const_logic_1;
        else 
            buffer_c3_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_c3_4_address0 <= zext_ln116_fu_342_p1(4 - 1 downto 0);
    buffer_c3_4_ce0 <= buffer_c3_4_ce0_local;

    buffer_c3_4_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_c3_4_ce0_local <= ap_const_logic_1;
        else 
            buffer_c3_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_c3_5_address0 <= zext_ln116_fu_342_p1(4 - 1 downto 0);
    buffer_c3_5_ce0 <= buffer_c3_5_ce0_local;

    buffer_c3_5_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_c3_5_ce0_local <= ap_const_logic_1;
        else 
            buffer_c3_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_c3_6_address0 <= zext_ln116_fu_342_p1(4 - 1 downto 0);
    buffer_c3_6_ce0 <= buffer_c3_6_ce0_local;

    buffer_c3_6_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_c3_6_ce0_local <= ap_const_logic_1;
        else 
            buffer_c3_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_c3_7_address0 <= zext_ln116_fu_342_p1(4 - 1 downto 0);
    buffer_c3_7_ce0 <= buffer_c3_7_ce0_local;

    buffer_c3_7_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_c3_7_ce0_local <= ap_const_logic_1;
        else 
            buffer_c3_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_c3_8_address0 <= zext_ln116_fu_342_p1(4 - 1 downto 0);
    buffer_c3_8_ce0 <= buffer_c3_8_ce0_local;

    buffer_c3_8_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_c3_8_ce0_local <= ap_const_logic_1;
        else 
            buffer_c3_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_c3_9_address0 <= zext_ln116_fu_342_p1(4 - 1 downto 0);
    buffer_c3_9_ce0 <= buffer_c3_9_ce0_local;

    buffer_c3_9_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_c3_9_ce0_local <= ap_const_logic_1;
        else 
            buffer_c3_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buffer_c3_address0 <= zext_ln116_fu_342_p1(4 - 1 downto 0);
    buffer_c3_ce0 <= buffer_c3_ce0_local;

    buffer_c3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_c3_ce0_local <= ap_const_logic_1;
        else 
            buffer_c3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_328_p3 <= 
        ap_const_lv5_1 when (icmp_ln117_fu_314_p2(0) = '1') else 
        ap_const_lv5_0;
    flatten_address0 <= zext_ln119_1_fu_469_p1(8 - 1 downto 0);
    flatten_ce0 <= flatten_ce0_local;

    flatten_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            flatten_ce0_local <= ap_const_logic_1;
        else 
            flatten_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    flatten_d0 <= tmp_s_reg_568;
    flatten_we0 <= flatten_we0_local;

    flatten_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            flatten_we0_local <= ap_const_logic_1;
        else 
            flatten_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln116_fu_291_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv8_C0) else "0";
    icmp_ln117_fu_314_p2 <= "1" when (j_fu_92 = ap_const_lv4_C) else "0";
    p_shl_fu_362_p3 <= (trunc_ln119_fu_358_p1 & ap_const_lv4_0);
    select_ln116_fu_320_p3 <= 
        ap_const_lv4_0 when (icmp_ln117_fu_314_p2(0) = '1') else 
        j_fu_92;
    sub_ln119_fu_382_p2 <= std_logic_vector(unsigned(p_shl_fu_362_p3) - unsigned(zext_ln119_fu_378_p1));
    tmp_fu_370_p3 <= (add_ln116_1_fu_336_p2 & ap_const_lv2_0);
    tmp_s_fu_414_p25 <= "XXXXXXX";
    trunc_ln119_fu_358_p1 <= add_ln116_1_fu_336_p2(4 - 1 downto 0);
    zext_ln116_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln116_1_fu_336_p2),64));
    zext_ln117_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln116_fu_320_p3),8));
    zext_ln119_1_fu_469_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln119_reg_563_pp0_iter2_reg),64));
    zext_ln119_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_370_p3),8));
end behav;
