// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_146_13_VITIS_LOOP_147_14 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buffer_c3_address0,
        buffer_c3_ce0,
        buffer_c3_q0,
        buffer_c3_1_address0,
        buffer_c3_1_ce0,
        buffer_c3_1_q0,
        buffer_c3_2_address0,
        buffer_c3_2_ce0,
        buffer_c3_2_q0,
        buffer_c3_3_address0,
        buffer_c3_3_ce0,
        buffer_c3_3_q0,
        buffer_c3_4_address0,
        buffer_c3_4_ce0,
        buffer_c3_4_q0,
        buffer_c3_5_address0,
        buffer_c3_5_ce0,
        buffer_c3_5_q0,
        buffer_c3_6_address0,
        buffer_c3_6_ce0,
        buffer_c3_6_q0,
        buffer_c3_7_address0,
        buffer_c3_7_ce0,
        buffer_c3_7_q0,
        buffer_c3_8_address0,
        buffer_c3_8_ce0,
        buffer_c3_8_q0,
        buffer_c3_9_address0,
        buffer_c3_9_ce0,
        buffer_c3_9_q0,
        buffer_c3_10_address0,
        buffer_c3_10_ce0,
        buffer_c3_10_q0,
        buffer_c3_11_address0,
        buffer_c3_11_ce0,
        buffer_c3_11_q0,
        buffer_c3_12_address0,
        buffer_c3_12_ce0,
        buffer_c3_12_q0,
        buffer_c3_13_address0,
        buffer_c3_13_ce0,
        buffer_c3_13_q0,
        buffer_c3_14_address0,
        buffer_c3_14_ce0,
        buffer_c3_14_q0,
        buffer_c3_15_address0,
        buffer_c3_15_ce0,
        buffer_c3_15_q0,
        flatten_address0,
        flatten_ce0,
        flatten_we0,
        flatten_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] buffer_c3_address0;
output   buffer_c3_ce0;
input  [6:0] buffer_c3_q0;
output  [3:0] buffer_c3_1_address0;
output   buffer_c3_1_ce0;
input  [6:0] buffer_c3_1_q0;
output  [3:0] buffer_c3_2_address0;
output   buffer_c3_2_ce0;
input  [6:0] buffer_c3_2_q0;
output  [3:0] buffer_c3_3_address0;
output   buffer_c3_3_ce0;
input  [6:0] buffer_c3_3_q0;
output  [3:0] buffer_c3_4_address0;
output   buffer_c3_4_ce0;
input  [6:0] buffer_c3_4_q0;
output  [3:0] buffer_c3_5_address0;
output   buffer_c3_5_ce0;
input  [6:0] buffer_c3_5_q0;
output  [3:0] buffer_c3_6_address0;
output   buffer_c3_6_ce0;
input  [6:0] buffer_c3_6_q0;
output  [3:0] buffer_c3_7_address0;
output   buffer_c3_7_ce0;
input  [6:0] buffer_c3_7_q0;
output  [3:0] buffer_c3_8_address0;
output   buffer_c3_8_ce0;
input  [6:0] buffer_c3_8_q0;
output  [3:0] buffer_c3_9_address0;
output   buffer_c3_9_ce0;
input  [6:0] buffer_c3_9_q0;
output  [3:0] buffer_c3_10_address0;
output   buffer_c3_10_ce0;
input  [6:0] buffer_c3_10_q0;
output  [3:0] buffer_c3_11_address0;
output   buffer_c3_11_ce0;
input  [6:0] buffer_c3_11_q0;
output  [3:0] buffer_c3_12_address0;
output   buffer_c3_12_ce0;
input  [6:0] buffer_c3_12_q0;
output  [3:0] buffer_c3_13_address0;
output   buffer_c3_13_ce0;
input  [6:0] buffer_c3_13_q0;
output  [3:0] buffer_c3_14_address0;
output   buffer_c3_14_ce0;
input  [6:0] buffer_c3_14_q0;
output  [3:0] buffer_c3_15_address0;
output   buffer_c3_15_ce0;
input  [6:0] buffer_c3_15_q0;
output  [7:0] flatten_address0;
output   flatten_ce0;
output   flatten_we0;
output  [6:0] flatten_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln146_fu_357_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [0:0] icmp_ln147_fu_372_p2;
reg   [0:0] icmp_ln147_reg_584;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] select_ln146_fu_378_p3;
reg   [3:0] select_ln146_reg_589;
wire   [63:0] zext_ln147_1_fu_386_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln149_fu_550_p1;
reg   [3:0] j_fu_106;
wire   [3:0] add_ln147_fu_406_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_j_load;
reg   [4:0] i_1_fu_110;
wire   [4:0] add_ln146_1_fu_432_p2;
reg   [7:0] indvar_flatten20_fu_114;
wire   [7:0] add_ln146_fu_363_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten20_load;
reg    buffer_c3_ce0_local;
reg    buffer_c3_1_ce0_local;
reg    buffer_c3_2_ce0_local;
reg    buffer_c3_3_ce0_local;
reg    buffer_c3_4_ce0_local;
reg    buffer_c3_5_ce0_local;
reg    buffer_c3_6_ce0_local;
reg    buffer_c3_7_ce0_local;
reg    buffer_c3_8_ce0_local;
reg    buffer_c3_9_ce0_local;
reg    buffer_c3_10_ce0_local;
reg    buffer_c3_11_ce0_local;
reg    buffer_c3_12_ce0_local;
reg    buffer_c3_13_ce0_local;
reg    buffer_c3_14_ce0_local;
reg    buffer_c3_15_ce0_local;
reg    flatten_we0_local;
wire   [6:0] tmp_s_fu_471_p35;
reg    flatten_ce0_local;
wire   [4:0] empty_fu_425_p3;
wire   [3:0] trunc_ln146_fu_438_p1;
wire   [6:0] tmp_fu_450_p3;
wire   [7:0] p_shl_fu_442_p3;
wire   [7:0] zext_ln147_fu_458_p1;
wire   [6:0] tmp_s_fu_471_p33;
wire   [7:0] zext_ln147_2_fu_468_p1;
wire   [7:0] sub_ln147_fu_462_p2;
wire   [7:0] add_ln149_fu_544_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] tmp_s_fu_471_p1;
wire   [3:0] tmp_s_fu_471_p3;
wire   [3:0] tmp_s_fu_471_p5;
wire   [3:0] tmp_s_fu_471_p7;
wire   [3:0] tmp_s_fu_471_p9;
wire   [3:0] tmp_s_fu_471_p11;
wire   [3:0] tmp_s_fu_471_p13;
wire   [3:0] tmp_s_fu_471_p15;
wire  signed [3:0] tmp_s_fu_471_p17;
wire  signed [3:0] tmp_s_fu_471_p19;
wire  signed [3:0] tmp_s_fu_471_p21;
wire  signed [3:0] tmp_s_fu_471_p23;
wire  signed [3:0] tmp_s_fu_471_p25;
wire  signed [3:0] tmp_s_fu_471_p27;
wire  signed [3:0] tmp_s_fu_471_p29;
wire  signed [3:0] tmp_s_fu_471_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 j_fu_106 = 4'd0;
#0 i_1_fu_110 = 5'd0;
#0 indvar_flatten20_fu_114 = 8'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) tiny_ecg_inference_sparsemux_33_4_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 7 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 7 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 7 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 7 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 7 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 7 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 7 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 7 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 7 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 7 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 7 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 7 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 7 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 7 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 7 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 7 ),
    .def_WIDTH( 7 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 7 ))
sparsemux_33_4_7_1_1_U502(
    .din0(buffer_c3_q0),
    .din1(buffer_c3_1_q0),
    .din2(buffer_c3_2_q0),
    .din3(buffer_c3_3_q0),
    .din4(buffer_c3_4_q0),
    .din5(buffer_c3_5_q0),
    .din6(buffer_c3_6_q0),
    .din7(buffer_c3_7_q0),
    .din8(buffer_c3_8_q0),
    .din9(buffer_c3_9_q0),
    .din10(buffer_c3_10_q0),
    .din11(buffer_c3_11_q0),
    .din12(buffer_c3_12_q0),
    .din13(buffer_c3_13_q0),
    .din14(buffer_c3_14_q0),
    .din15(buffer_c3_15_q0),
    .def(tmp_s_fu_471_p33),
    .sel(trunc_ln146_fu_438_p1),
    .dout(tmp_s_fu_471_p35)
);

tiny_ecg_inference_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_1_fu_110 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_1_fu_110 <= add_ln146_1_fu_432_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln146_fu_357_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten20_fu_114 <= add_ln146_fu_363_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten20_fu_114 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln146_fu_357_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_106 <= add_ln147_fu_406_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_106 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln147_reg_584 <= icmp_ln147_fu_372_p2;
        select_ln146_reg_589 <= select_ln146_fu_378_p3;
    end
end

always @ (*) begin
    if (((icmp_ln146_fu_357_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten20_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten20_load = indvar_flatten20_fu_114;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 4'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_10_ce0_local = 1'b1;
    end else begin
        buffer_c3_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_11_ce0_local = 1'b1;
    end else begin
        buffer_c3_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_12_ce0_local = 1'b1;
    end else begin
        buffer_c3_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_13_ce0_local = 1'b1;
    end else begin
        buffer_c3_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_14_ce0_local = 1'b1;
    end else begin
        buffer_c3_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_15_ce0_local = 1'b1;
    end else begin
        buffer_c3_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_1_ce0_local = 1'b1;
    end else begin
        buffer_c3_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_2_ce0_local = 1'b1;
    end else begin
        buffer_c3_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_3_ce0_local = 1'b1;
    end else begin
        buffer_c3_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_4_ce0_local = 1'b1;
    end else begin
        buffer_c3_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_5_ce0_local = 1'b1;
    end else begin
        buffer_c3_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_6_ce0_local = 1'b1;
    end else begin
        buffer_c3_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_7_ce0_local = 1'b1;
    end else begin
        buffer_c3_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_8_ce0_local = 1'b1;
    end else begin
        buffer_c3_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_9_ce0_local = 1'b1;
    end else begin
        buffer_c3_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_ce0_local = 1'b1;
    end else begin
        buffer_c3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        flatten_ce0_local = 1'b1;
    end else begin
        flatten_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        flatten_we0_local = 1'b1;
    end else begin
        flatten_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln146_1_fu_432_p2 = (i_1_fu_110 + empty_fu_425_p3);

assign add_ln146_fu_363_p2 = (ap_sig_allocacmp_indvar_flatten20_load + 8'd1);

assign add_ln147_fu_406_p2 = (select_ln146_fu_378_p3 + 4'd1);

assign add_ln149_fu_544_p2 = (zext_ln147_2_fu_468_p1 + sub_ln147_fu_462_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign buffer_c3_10_address0 = zext_ln147_1_fu_386_p1;

assign buffer_c3_10_ce0 = buffer_c3_10_ce0_local;

assign buffer_c3_11_address0 = zext_ln147_1_fu_386_p1;

assign buffer_c3_11_ce0 = buffer_c3_11_ce0_local;

assign buffer_c3_12_address0 = zext_ln147_1_fu_386_p1;

assign buffer_c3_12_ce0 = buffer_c3_12_ce0_local;

assign buffer_c3_13_address0 = zext_ln147_1_fu_386_p1;

assign buffer_c3_13_ce0 = buffer_c3_13_ce0_local;

assign buffer_c3_14_address0 = zext_ln147_1_fu_386_p1;

assign buffer_c3_14_ce0 = buffer_c3_14_ce0_local;

assign buffer_c3_15_address0 = zext_ln147_1_fu_386_p1;

assign buffer_c3_15_ce0 = buffer_c3_15_ce0_local;

assign buffer_c3_1_address0 = zext_ln147_1_fu_386_p1;

assign buffer_c3_1_ce0 = buffer_c3_1_ce0_local;

assign buffer_c3_2_address0 = zext_ln147_1_fu_386_p1;

assign buffer_c3_2_ce0 = buffer_c3_2_ce0_local;

assign buffer_c3_3_address0 = zext_ln147_1_fu_386_p1;

assign buffer_c3_3_ce0 = buffer_c3_3_ce0_local;

assign buffer_c3_4_address0 = zext_ln147_1_fu_386_p1;

assign buffer_c3_4_ce0 = buffer_c3_4_ce0_local;

assign buffer_c3_5_address0 = zext_ln147_1_fu_386_p1;

assign buffer_c3_5_ce0 = buffer_c3_5_ce0_local;

assign buffer_c3_6_address0 = zext_ln147_1_fu_386_p1;

assign buffer_c3_6_ce0 = buffer_c3_6_ce0_local;

assign buffer_c3_7_address0 = zext_ln147_1_fu_386_p1;

assign buffer_c3_7_ce0 = buffer_c3_7_ce0_local;

assign buffer_c3_8_address0 = zext_ln147_1_fu_386_p1;

assign buffer_c3_8_ce0 = buffer_c3_8_ce0_local;

assign buffer_c3_9_address0 = zext_ln147_1_fu_386_p1;

assign buffer_c3_9_ce0 = buffer_c3_9_ce0_local;

assign buffer_c3_address0 = zext_ln147_1_fu_386_p1;

assign buffer_c3_ce0 = buffer_c3_ce0_local;

assign empty_fu_425_p3 = ((icmp_ln147_reg_584[0:0] == 1'b1) ? 5'd1 : 5'd0);

assign flatten_address0 = zext_ln149_fu_550_p1;

assign flatten_ce0 = flatten_ce0_local;

assign flatten_d0 = tmp_s_fu_471_p35;

assign flatten_we0 = flatten_we0_local;

assign icmp_ln146_fu_357_p2 = ((ap_sig_allocacmp_indvar_flatten20_load == 8'd192) ? 1'b1 : 1'b0);

assign icmp_ln147_fu_372_p2 = ((ap_sig_allocacmp_j_load == 4'd12) ? 1'b1 : 1'b0);

assign p_shl_fu_442_p3 = {{trunc_ln146_fu_438_p1}, {4'd0}};

assign select_ln146_fu_378_p3 = ((icmp_ln147_fu_372_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_j_load);

assign sub_ln147_fu_462_p2 = (p_shl_fu_442_p3 - zext_ln147_fu_458_p1);

assign tmp_fu_450_p3 = {{add_ln146_1_fu_432_p2}, {2'd0}};

assign tmp_s_fu_471_p33 = 'bx;

assign trunc_ln146_fu_438_p1 = add_ln146_1_fu_432_p2[3:0];

assign zext_ln147_1_fu_386_p1 = select_ln146_fu_378_p3;

assign zext_ln147_2_fu_468_p1 = select_ln146_reg_589;

assign zext_ln147_fu_458_p1 = tmp_fu_450_p3;

assign zext_ln149_fu_550_p1 = add_ln149_fu_544_p2;

endmodule //tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_146_13_VITIS_LOOP_147_14
