-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_61_2_conv1_weight_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 40
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);
 
          address2        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce2             : in std_logic; 
          q2              : out std_logic_vector(DataWidth-1 downto 0);
 
          address3        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce3             : in std_logic; 
          q3              : out std_logic_vector(DataWidth-1 downto 0);
 
          address4        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce4             : in std_logic; 
          q4              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_61_2_conv1_weight_ROM_AUTO_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address2_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address3_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address4_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10000001", 1 => "10001000", 2 => "10110100", 3 => "01010010", 
    4 => "01001110", 5 => "00101101", 6 => "11101000", 7 => "10000000", 
    8 => "01011001", 9 => "11001110", 10 => "10100001", 11 => "10010000", 
    12 => "11111010", 13 => "01110101", 14 => "01111111", 15 => "11101100", 
    16 => "00001111", 17 => "10111001", 18 => "00100101", 19 => "10000000", 
    20 => "01111001", 21 => "11111010", 22 => "01110011", 23 => "10000011", 
    24 => "00011110", 25 => "00101001", 26 => "11111111", 27 => "01111111", 
    28 => "01010110", 29 => "01111000", 30 => "11101000", 31 => "01111111", 
    32 => "11011000", 33 => "11110111", 34 => "10000101", 35 => "11011100", 
    36 => "10100011", 37 => "11110111", 38 => "11101001", 39 => "01111111");

signal mem1 : mem_array := (
    0 => "10000001", 1 => "10001000", 2 => "10110100", 3 => "01010010", 
    4 => "01001110", 5 => "00101101", 6 => "11101000", 7 => "10000000", 
    8 => "01011001", 9 => "11001110", 10 => "10100001", 11 => "10010000", 
    12 => "11111010", 13 => "01110101", 14 => "01111111", 15 => "11101100", 
    16 => "00001111", 17 => "10111001", 18 => "00100101", 19 => "10000000", 
    20 => "01111001", 21 => "11111010", 22 => "01110011", 23 => "10000011", 
    24 => "00011110", 25 => "00101001", 26 => "11111111", 27 => "01111111", 
    28 => "01010110", 29 => "01111000", 30 => "11101000", 31 => "01111111", 
    32 => "11011000", 33 => "11110111", 34 => "10000101", 35 => "11011100", 
    36 => "10100011", 37 => "11110111", 38 => "11101001", 39 => "01111111");

signal mem2 : mem_array := (
    0 => "10000001", 1 => "10001000", 2 => "10110100", 3 => "01010010", 
    4 => "01001110", 5 => "00101101", 6 => "11101000", 7 => "10000000", 
    8 => "01011001", 9 => "11001110", 10 => "10100001", 11 => "10010000", 
    12 => "11111010", 13 => "01110101", 14 => "01111111", 15 => "11101100", 
    16 => "00001111", 17 => "10111001", 18 => "00100101", 19 => "10000000", 
    20 => "01111001", 21 => "11111010", 22 => "01110011", 23 => "10000011", 
    24 => "00011110", 25 => "00101001", 26 => "11111111", 27 => "01111111", 
    28 => "01010110", 29 => "01111000", 30 => "11101000", 31 => "01111111", 
    32 => "11011000", 33 => "11110111", 34 => "10000101", 35 => "11011100", 
    36 => "10100011", 37 => "11110111", 38 => "11101001", 39 => "01111111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_2: process (address2) 
begin
      address2_tmp <= address2;
--synthesis translate_off
      if (CONV_INTEGER(address2) > AddressRange-1) then
           address2_tmp <= (others => '0');
      else 
           address2_tmp <= address2;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_3: process (address3) 
begin
      address3_tmp <= address3;
--synthesis translate_off
      if (CONV_INTEGER(address3) > AddressRange-1) then
           address3_tmp <= (others => '0');
      else 
           address3_tmp <= address3;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_4: process (address4) 
begin
      address4_tmp <= address4;
--synthesis translate_off
      if (CONV_INTEGER(address4) > AddressRange-1) then
           address4_tmp <= (others => '0');
      else 
           address4_tmp <= address4;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;
 
        if (ce2 = '1') then  
            q2 <= mem1(CONV_INTEGER(address2_tmp)); 
        end if;
 
        if (ce3 = '1') then  
            q3 <= mem1(CONV_INTEGER(address3_tmp)); 
        end if;
 
        if (ce4 = '1') then  
            q4 <= mem2(CONV_INTEGER(address4_tmp)); 
        end if;

end if;
end process;

end rtl;

