// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_49_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_DATA_IN_0_AWVALID,
        m_axi_DATA_IN_0_AWREADY,
        m_axi_DATA_IN_0_AWADDR,
        m_axi_DATA_IN_0_AWID,
        m_axi_DATA_IN_0_AWLEN,
        m_axi_DATA_IN_0_AWSIZE,
        m_axi_DATA_IN_0_AWBURST,
        m_axi_DATA_IN_0_AWLOCK,
        m_axi_DATA_IN_0_AWCACHE,
        m_axi_DATA_IN_0_AWPROT,
        m_axi_DATA_IN_0_AWQOS,
        m_axi_DATA_IN_0_AWREGION,
        m_axi_DATA_IN_0_AWUSER,
        m_axi_DATA_IN_0_WVALID,
        m_axi_DATA_IN_0_WREADY,
        m_axi_DATA_IN_0_WDATA,
        m_axi_DATA_IN_0_WSTRB,
        m_axi_DATA_IN_0_WLAST,
        m_axi_DATA_IN_0_WID,
        m_axi_DATA_IN_0_WUSER,
        m_axi_DATA_IN_0_ARVALID,
        m_axi_DATA_IN_0_ARREADY,
        m_axi_DATA_IN_0_ARADDR,
        m_axi_DATA_IN_0_ARID,
        m_axi_DATA_IN_0_ARLEN,
        m_axi_DATA_IN_0_ARSIZE,
        m_axi_DATA_IN_0_ARBURST,
        m_axi_DATA_IN_0_ARLOCK,
        m_axi_DATA_IN_0_ARCACHE,
        m_axi_DATA_IN_0_ARPROT,
        m_axi_DATA_IN_0_ARQOS,
        m_axi_DATA_IN_0_ARREGION,
        m_axi_DATA_IN_0_ARUSER,
        m_axi_DATA_IN_0_RVALID,
        m_axi_DATA_IN_0_RREADY,
        m_axi_DATA_IN_0_RDATA,
        m_axi_DATA_IN_0_RLAST,
        m_axi_DATA_IN_0_RID,
        m_axi_DATA_IN_0_RFIFONUM,
        m_axi_DATA_IN_0_RUSER,
        m_axi_DATA_IN_0_RRESP,
        m_axi_DATA_IN_0_BVALID,
        m_axi_DATA_IN_0_BREADY,
        m_axi_DATA_IN_0_BRESP,
        m_axi_DATA_IN_0_BID,
        m_axi_DATA_IN_0_BUSER,
        input_ecg,
        local_ecg_4_address0,
        local_ecg_4_ce0,
        local_ecg_4_we0,
        local_ecg_4_d0,
        local_ecg_3_address0,
        local_ecg_3_ce0,
        local_ecg_3_we0,
        local_ecg_3_d0,
        local_ecg_2_address0,
        local_ecg_2_ce0,
        local_ecg_2_we0,
        local_ecg_2_d0,
        local_ecg_1_address0,
        local_ecg_1_ce0,
        local_ecg_1_we0,
        local_ecg_1_d0,
        local_ecg_address0,
        local_ecg_ce0,
        local_ecg_we0,
        local_ecg_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_DATA_IN_0_AWVALID;
input   m_axi_DATA_IN_0_AWREADY;
output  [63:0] m_axi_DATA_IN_0_AWADDR;
output  [0:0] m_axi_DATA_IN_0_AWID;
output  [31:0] m_axi_DATA_IN_0_AWLEN;
output  [2:0] m_axi_DATA_IN_0_AWSIZE;
output  [1:0] m_axi_DATA_IN_0_AWBURST;
output  [1:0] m_axi_DATA_IN_0_AWLOCK;
output  [3:0] m_axi_DATA_IN_0_AWCACHE;
output  [2:0] m_axi_DATA_IN_0_AWPROT;
output  [3:0] m_axi_DATA_IN_0_AWQOS;
output  [3:0] m_axi_DATA_IN_0_AWREGION;
output  [0:0] m_axi_DATA_IN_0_AWUSER;
output   m_axi_DATA_IN_0_WVALID;
input   m_axi_DATA_IN_0_WREADY;
output  [7:0] m_axi_DATA_IN_0_WDATA;
output  [0:0] m_axi_DATA_IN_0_WSTRB;
output   m_axi_DATA_IN_0_WLAST;
output  [0:0] m_axi_DATA_IN_0_WID;
output  [0:0] m_axi_DATA_IN_0_WUSER;
output   m_axi_DATA_IN_0_ARVALID;
input   m_axi_DATA_IN_0_ARREADY;
output  [63:0] m_axi_DATA_IN_0_ARADDR;
output  [0:0] m_axi_DATA_IN_0_ARID;
output  [31:0] m_axi_DATA_IN_0_ARLEN;
output  [2:0] m_axi_DATA_IN_0_ARSIZE;
output  [1:0] m_axi_DATA_IN_0_ARBURST;
output  [1:0] m_axi_DATA_IN_0_ARLOCK;
output  [3:0] m_axi_DATA_IN_0_ARCACHE;
output  [2:0] m_axi_DATA_IN_0_ARPROT;
output  [3:0] m_axi_DATA_IN_0_ARQOS;
output  [3:0] m_axi_DATA_IN_0_ARREGION;
output  [0:0] m_axi_DATA_IN_0_ARUSER;
input   m_axi_DATA_IN_0_RVALID;
output   m_axi_DATA_IN_0_RREADY;
input  [7:0] m_axi_DATA_IN_0_RDATA;
input   m_axi_DATA_IN_0_RLAST;
input  [0:0] m_axi_DATA_IN_0_RID;
input  [10:0] m_axi_DATA_IN_0_RFIFONUM;
input  [0:0] m_axi_DATA_IN_0_RUSER;
input  [1:0] m_axi_DATA_IN_0_RRESP;
input   m_axi_DATA_IN_0_BVALID;
output   m_axi_DATA_IN_0_BREADY;
input  [1:0] m_axi_DATA_IN_0_BRESP;
input  [0:0] m_axi_DATA_IN_0_BID;
input  [0:0] m_axi_DATA_IN_0_BUSER;
input  [63:0] input_ecg;
output  [4:0] local_ecg_4_address0;
output   local_ecg_4_ce0;
output   local_ecg_4_we0;
output  [7:0] local_ecg_4_d0;
output  [4:0] local_ecg_3_address0;
output   local_ecg_3_ce0;
output   local_ecg_3_we0;
output  [7:0] local_ecg_3_d0;
output  [4:0] local_ecg_2_address0;
output   local_ecg_2_ce0;
output   local_ecg_2_we0;
output  [7:0] local_ecg_2_d0;
output  [4:0] local_ecg_1_address0;
output   local_ecg_1_ce0;
output   local_ecg_1_we0;
output  [7:0] local_ecg_1_d0;
output  [4:0] local_ecg_address0;
output   local_ecg_ce0;
output   local_ecg_we0;
output  [7:0] local_ecg_d0;

reg ap_idle;
reg m_axi_DATA_IN_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln49_fu_187_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    DATA_IN_blk_n_R;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [2:0] trunc_ln49_fu_205_p1;
reg   [2:0] trunc_ln49_reg_314;
reg   [2:0] trunc_ln49_reg_314_pp0_iter1_reg;
reg   [7:0] DATA_IN_addr_read_reg_318;
wire   [63:0] zext_ln49_fu_270_p1;
wire    ap_block_pp0_stage0_grp0;
reg   [6:0] phi_urem_fu_78;
wire   [6:0] select_ln49_fu_233_p3;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_phi_urem_load;
wire    ap_block_pp0_stage0;
reg   [14:0] phi_mul_fu_82;
wire   [14:0] add_ln49_1_fu_254_p2;
reg   [6:0] i_fu_86;
wire   [6:0] add_ln49_fu_193_p2;
reg   [6:0] ap_sig_allocacmp_i_1;
reg    local_ecg_3_we0_local;
reg    local_ecg_3_ce0_local;
reg    local_ecg_2_we0_local;
reg    local_ecg_2_ce0_local;
reg    local_ecg_1_we0_local;
reg    local_ecg_1_ce0_local;
reg    local_ecg_we0_local;
reg    local_ecg_ce0_local;
reg    local_ecg_4_we0_local;
reg    local_ecg_4_ce0_local;
wire   [0:0] icmp_ln49_1_fu_227_p2;
wire   [6:0] add_ln49_2_fu_221_p2;
wire   [4:0] tmp_fu_260_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 phi_urem_fu_78 = 7'd0;
#0 phi_mul_fu_82 = 15'd0;
#0 i_fu_86 = 7'd0;
#0 ap_done_reg = 1'b0;
end

tiny_ecg_inference_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln49_fu_187_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_86 <= add_ln49_fu_193_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_86 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            phi_mul_fu_82 <= 15'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            phi_mul_fu_82 <= add_ln49_1_fu_254_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln49_fu_187_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            phi_urem_fu_78 <= select_ln49_fu_233_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_urem_fu_78 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DATA_IN_addr_read_reg_318 <= m_axi_DATA_IN_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        trunc_ln49_reg_314 <= trunc_ln49_fu_205_p1;
        trunc_ln49_reg_314_pp0_iter1_reg <= trunc_ln49_reg_314;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DATA_IN_blk_n_R = m_axi_DATA_IN_0_RVALID;
    end else begin
        DATA_IN_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln49_fu_187_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_phi_urem_load = 7'd0;
    end else begin
        ap_sig_allocacmp_phi_urem_load = phi_urem_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_ecg_1_ce0_local = 1'b1;
    end else begin
        local_ecg_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln49_reg_314_pp0_iter1_reg == 3'd1))) begin
        local_ecg_1_we0_local = 1'b1;
    end else begin
        local_ecg_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_ecg_2_ce0_local = 1'b1;
    end else begin
        local_ecg_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln49_reg_314_pp0_iter1_reg == 3'd2))) begin
        local_ecg_2_we0_local = 1'b1;
    end else begin
        local_ecg_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_ecg_3_ce0_local = 1'b1;
    end else begin
        local_ecg_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln49_reg_314_pp0_iter1_reg == 3'd3))) begin
        local_ecg_3_we0_local = 1'b1;
    end else begin
        local_ecg_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_ecg_4_ce0_local = 1'b1;
    end else begin
        local_ecg_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln49_reg_314_pp0_iter1_reg == 3'd0) & ~(trunc_ln49_reg_314_pp0_iter1_reg == 3'd1) & ~(trunc_ln49_reg_314_pp0_iter1_reg == 3'd2) & ~(trunc_ln49_reg_314_pp0_iter1_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_ecg_4_we0_local = 1'b1;
    end else begin
        local_ecg_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_ecg_ce0_local = 1'b1;
    end else begin
        local_ecg_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln49_reg_314_pp0_iter1_reg == 3'd0))) begin
        local_ecg_we0_local = 1'b1;
    end else begin
        local_ecg_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_DATA_IN_0_RREADY = 1'b1;
    end else begin
        m_axi_DATA_IN_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln49_1_fu_254_p2 = (phi_mul_fu_82 + 15'd205);

assign add_ln49_2_fu_221_p2 = (ap_sig_allocacmp_phi_urem_load + 7'd1);

assign add_ln49_fu_193_p2 = (ap_sig_allocacmp_i_1 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_DATA_IN_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((m_axi_DATA_IN_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_DATA_IN_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln49_1_fu_227_p2 = ((ap_sig_allocacmp_phi_urem_load == 7'd4) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_187_p2 = ((ap_sig_allocacmp_i_1 == 7'd90) ? 1'b1 : 1'b0);

assign local_ecg_1_address0 = zext_ln49_fu_270_p1;

assign local_ecg_1_ce0 = local_ecg_1_ce0_local;

assign local_ecg_1_d0 = DATA_IN_addr_read_reg_318;

assign local_ecg_1_we0 = local_ecg_1_we0_local;

assign local_ecg_2_address0 = zext_ln49_fu_270_p1;

assign local_ecg_2_ce0 = local_ecg_2_ce0_local;

assign local_ecg_2_d0 = DATA_IN_addr_read_reg_318;

assign local_ecg_2_we0 = local_ecg_2_we0_local;

assign local_ecg_3_address0 = zext_ln49_fu_270_p1;

assign local_ecg_3_ce0 = local_ecg_3_ce0_local;

assign local_ecg_3_d0 = DATA_IN_addr_read_reg_318;

assign local_ecg_3_we0 = local_ecg_3_we0_local;

assign local_ecg_4_address0 = zext_ln49_fu_270_p1;

assign local_ecg_4_ce0 = local_ecg_4_ce0_local;

assign local_ecg_4_d0 = DATA_IN_addr_read_reg_318;

assign local_ecg_4_we0 = local_ecg_4_we0_local;

assign local_ecg_address0 = zext_ln49_fu_270_p1;

assign local_ecg_ce0 = local_ecg_ce0_local;

assign local_ecg_d0 = DATA_IN_addr_read_reg_318;

assign local_ecg_we0 = local_ecg_we0_local;

assign m_axi_DATA_IN_0_ARADDR = 64'd0;

assign m_axi_DATA_IN_0_ARBURST = 2'd0;

assign m_axi_DATA_IN_0_ARCACHE = 4'd0;

assign m_axi_DATA_IN_0_ARID = 1'd0;

assign m_axi_DATA_IN_0_ARLEN = 32'd0;

assign m_axi_DATA_IN_0_ARLOCK = 2'd0;

assign m_axi_DATA_IN_0_ARPROT = 3'd0;

assign m_axi_DATA_IN_0_ARQOS = 4'd0;

assign m_axi_DATA_IN_0_ARREGION = 4'd0;

assign m_axi_DATA_IN_0_ARSIZE = 3'd0;

assign m_axi_DATA_IN_0_ARUSER = 1'd0;

assign m_axi_DATA_IN_0_ARVALID = 1'b0;

assign m_axi_DATA_IN_0_AWADDR = 64'd0;

assign m_axi_DATA_IN_0_AWBURST = 2'd0;

assign m_axi_DATA_IN_0_AWCACHE = 4'd0;

assign m_axi_DATA_IN_0_AWID = 1'd0;

assign m_axi_DATA_IN_0_AWLEN = 32'd0;

assign m_axi_DATA_IN_0_AWLOCK = 2'd0;

assign m_axi_DATA_IN_0_AWPROT = 3'd0;

assign m_axi_DATA_IN_0_AWQOS = 4'd0;

assign m_axi_DATA_IN_0_AWREGION = 4'd0;

assign m_axi_DATA_IN_0_AWSIZE = 3'd0;

assign m_axi_DATA_IN_0_AWUSER = 1'd0;

assign m_axi_DATA_IN_0_AWVALID = 1'b0;

assign m_axi_DATA_IN_0_BREADY = 1'b0;

assign m_axi_DATA_IN_0_WDATA = 8'd0;

assign m_axi_DATA_IN_0_WID = 1'd0;

assign m_axi_DATA_IN_0_WLAST = 1'b0;

assign m_axi_DATA_IN_0_WSTRB = 1'd0;

assign m_axi_DATA_IN_0_WUSER = 1'd0;

assign m_axi_DATA_IN_0_WVALID = 1'b0;

assign select_ln49_fu_233_p3 = ((icmp_ln49_1_fu_227_p2[0:0] == 1'b1) ? 7'd0 : add_ln49_2_fu_221_p2);

assign tmp_fu_260_p4 = {{phi_mul_fu_82[14:10]}};

assign trunc_ln49_fu_205_p1 = ap_sig_allocacmp_phi_urem_load[2:0];

assign zext_ln49_fu_270_p1 = tmp_fu_260_p4;

endmodule //tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_49_1
