// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_116_12_VITIS_LOOP_117_13 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buffer_c3_address0,
        buffer_c3_ce0,
        buffer_c3_q0,
        buffer_c3_1_address0,
        buffer_c3_1_ce0,
        buffer_c3_1_q0,
        buffer_c3_2_address0,
        buffer_c3_2_ce0,
        buffer_c3_2_q0,
        buffer_c3_3_address0,
        buffer_c3_3_ce0,
        buffer_c3_3_q0,
        buffer_c3_4_address0,
        buffer_c3_4_ce0,
        buffer_c3_4_q0,
        buffer_c3_5_address0,
        buffer_c3_5_ce0,
        buffer_c3_5_q0,
        buffer_c3_6_address0,
        buffer_c3_6_ce0,
        buffer_c3_6_q0,
        buffer_c3_7_address0,
        buffer_c3_7_ce0,
        buffer_c3_7_q0,
        buffer_c3_8_address0,
        buffer_c3_8_ce0,
        buffer_c3_8_q0,
        buffer_c3_9_address0,
        buffer_c3_9_ce0,
        buffer_c3_9_q0,
        buffer_c3_10_address0,
        buffer_c3_10_ce0,
        buffer_c3_10_q0,
        buffer_c3_11_address0,
        buffer_c3_11_ce0,
        buffer_c3_11_q0,
        flatten_address0,
        flatten_ce0,
        flatten_we0,
        flatten_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] buffer_c3_address0;
output   buffer_c3_ce0;
input  [6:0] buffer_c3_q0;
output  [3:0] buffer_c3_1_address0;
output   buffer_c3_1_ce0;
input  [6:0] buffer_c3_1_q0;
output  [3:0] buffer_c3_2_address0;
output   buffer_c3_2_ce0;
input  [6:0] buffer_c3_2_q0;
output  [3:0] buffer_c3_3_address0;
output   buffer_c3_3_ce0;
input  [6:0] buffer_c3_3_q0;
output  [3:0] buffer_c3_4_address0;
output   buffer_c3_4_ce0;
input  [6:0] buffer_c3_4_q0;
output  [3:0] buffer_c3_5_address0;
output   buffer_c3_5_ce0;
input  [6:0] buffer_c3_5_q0;
output  [3:0] buffer_c3_6_address0;
output   buffer_c3_6_ce0;
input  [6:0] buffer_c3_6_q0;
output  [3:0] buffer_c3_7_address0;
output   buffer_c3_7_ce0;
input  [6:0] buffer_c3_7_q0;
output  [3:0] buffer_c3_8_address0;
output   buffer_c3_8_ce0;
input  [6:0] buffer_c3_8_q0;
output  [3:0] buffer_c3_9_address0;
output   buffer_c3_9_ce0;
input  [6:0] buffer_c3_9_q0;
output  [3:0] buffer_c3_10_address0;
output   buffer_c3_10_ce0;
input  [6:0] buffer_c3_10_q0;
output  [3:0] buffer_c3_11_address0;
output   buffer_c3_11_ce0;
input  [6:0] buffer_c3_11_q0;
output  [7:0] flatten_address0;
output   flatten_ce0;
output   flatten_we0;
output  [6:0] flatten_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln116_fu_291_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] select_ln116_fu_320_p3;
reg   [3:0] select_ln116_reg_498;
wire   [7:0] add_ln119_fu_392_p2;
reg   [7:0] add_ln119_reg_563;
reg   [7:0] add_ln119_reg_563_pp0_iter2_reg;
wire   [6:0] tmp_s_fu_414_p27;
reg   [6:0] tmp_s_reg_568;
wire   [63:0] zext_ln116_fu_342_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln119_1_fu_469_p1;
reg   [3:0] j_fu_92;
wire   [3:0] add_ln117_fu_398_p2;
wire    ap_loop_init;
reg   [4:0] i_fu_96;
wire   [4:0] add_ln116_1_fu_336_p2;
reg   [7:0] indvar_flatten_fu_100;
wire   [7:0] add_ln116_fu_297_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten_load;
reg    buffer_c3_ce0_local;
reg    buffer_c3_1_ce0_local;
reg    buffer_c3_2_ce0_local;
reg    buffer_c3_3_ce0_local;
reg    buffer_c3_4_ce0_local;
reg    buffer_c3_5_ce0_local;
reg    buffer_c3_6_ce0_local;
reg    buffer_c3_7_ce0_local;
reg    buffer_c3_8_ce0_local;
reg    buffer_c3_9_ce0_local;
reg    buffer_c3_10_ce0_local;
reg    buffer_c3_11_ce0_local;
reg    flatten_we0_local;
reg    flatten_ce0_local;
wire   [0:0] icmp_ln117_fu_314_p2;
wire   [4:0] empty_fu_328_p3;
wire   [3:0] trunc_ln119_fu_358_p1;
wire   [6:0] tmp_fu_370_p3;
wire   [7:0] p_shl_fu_362_p3;
wire   [7:0] zext_ln119_fu_378_p1;
wire   [7:0] zext_ln117_fu_388_p1;
wire   [7:0] sub_ln119_fu_382_p2;
wire   [6:0] tmp_s_fu_414_p25;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] tmp_s_fu_414_p1;
wire   [3:0] tmp_s_fu_414_p3;
wire   [3:0] tmp_s_fu_414_p5;
wire   [3:0] tmp_s_fu_414_p7;
wire   [3:0] tmp_s_fu_414_p9;
wire   [3:0] tmp_s_fu_414_p11;
wire   [3:0] tmp_s_fu_414_p13;
wire   [3:0] tmp_s_fu_414_p15;
wire  signed [3:0] tmp_s_fu_414_p17;
wire  signed [3:0] tmp_s_fu_414_p19;
wire  signed [3:0] tmp_s_fu_414_p21;
wire  signed [3:0] tmp_s_fu_414_p23;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 j_fu_92 = 4'd0;
#0 i_fu_96 = 5'd0;
#0 indvar_flatten_fu_100 = 8'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) tiny_ecg_inference_sparsemux_25_4_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 7 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 7 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 7 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 7 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 7 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 7 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 7 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 7 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 7 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 7 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 7 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 7 ),
    .def_WIDTH( 7 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 7 ))
sparsemux_25_4_7_1_1_U3272(
    .din0(buffer_c3_q0),
    .din1(buffer_c3_1_q0),
    .din2(buffer_c3_2_q0),
    .din3(buffer_c3_3_q0),
    .din4(buffer_c3_4_q0),
    .din5(buffer_c3_5_q0),
    .din6(buffer_c3_6_q0),
    .din7(buffer_c3_7_q0),
    .din8(buffer_c3_8_q0),
    .din9(buffer_c3_9_q0),
    .din10(buffer_c3_10_q0),
    .din11(buffer_c3_11_q0),
    .def(tmp_s_fu_414_p25),
    .sel(select_ln116_reg_498),
    .dout(tmp_s_fu_414_p27)
);

tiny_ecg_inference_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_96 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_96 <= add_ln116_1_fu_336_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln116_fu_291_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_100 <= add_ln116_fu_297_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_100 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_92 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_92 <= add_ln117_fu_398_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln119_reg_563 <= add_ln119_fu_392_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        select_ln116_reg_498 <= select_ln116_fu_320_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln119_reg_563_pp0_iter2_reg <= add_ln119_reg_563;
        tmp_s_reg_568 <= tmp_s_fu_414_p27;
    end
end

always @ (*) begin
    if (((icmp_ln116_fu_291_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_10_ce0_local = 1'b1;
    end else begin
        buffer_c3_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_11_ce0_local = 1'b1;
    end else begin
        buffer_c3_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_1_ce0_local = 1'b1;
    end else begin
        buffer_c3_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_2_ce0_local = 1'b1;
    end else begin
        buffer_c3_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_3_ce0_local = 1'b1;
    end else begin
        buffer_c3_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_4_ce0_local = 1'b1;
    end else begin
        buffer_c3_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_5_ce0_local = 1'b1;
    end else begin
        buffer_c3_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_6_ce0_local = 1'b1;
    end else begin
        buffer_c3_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_7_ce0_local = 1'b1;
    end else begin
        buffer_c3_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_8_ce0_local = 1'b1;
    end else begin
        buffer_c3_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_9_ce0_local = 1'b1;
    end else begin
        buffer_c3_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_c3_ce0_local = 1'b1;
    end else begin
        buffer_c3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        flatten_ce0_local = 1'b1;
    end else begin
        flatten_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        flatten_we0_local = 1'b1;
    end else begin
        flatten_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln116_1_fu_336_p2 = (i_fu_96 + empty_fu_328_p3);

assign add_ln116_fu_297_p2 = (ap_sig_allocacmp_indvar_flatten_load + 8'd1);

assign add_ln117_fu_398_p2 = (select_ln116_fu_320_p3 + 4'd1);

assign add_ln119_fu_392_p2 = (zext_ln117_fu_388_p1 + sub_ln119_fu_382_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign buffer_c3_10_address0 = zext_ln116_fu_342_p1;

assign buffer_c3_10_ce0 = buffer_c3_10_ce0_local;

assign buffer_c3_11_address0 = zext_ln116_fu_342_p1;

assign buffer_c3_11_ce0 = buffer_c3_11_ce0_local;

assign buffer_c3_1_address0 = zext_ln116_fu_342_p1;

assign buffer_c3_1_ce0 = buffer_c3_1_ce0_local;

assign buffer_c3_2_address0 = zext_ln116_fu_342_p1;

assign buffer_c3_2_ce0 = buffer_c3_2_ce0_local;

assign buffer_c3_3_address0 = zext_ln116_fu_342_p1;

assign buffer_c3_3_ce0 = buffer_c3_3_ce0_local;

assign buffer_c3_4_address0 = zext_ln116_fu_342_p1;

assign buffer_c3_4_ce0 = buffer_c3_4_ce0_local;

assign buffer_c3_5_address0 = zext_ln116_fu_342_p1;

assign buffer_c3_5_ce0 = buffer_c3_5_ce0_local;

assign buffer_c3_6_address0 = zext_ln116_fu_342_p1;

assign buffer_c3_6_ce0 = buffer_c3_6_ce0_local;

assign buffer_c3_7_address0 = zext_ln116_fu_342_p1;

assign buffer_c3_7_ce0 = buffer_c3_7_ce0_local;

assign buffer_c3_8_address0 = zext_ln116_fu_342_p1;

assign buffer_c3_8_ce0 = buffer_c3_8_ce0_local;

assign buffer_c3_9_address0 = zext_ln116_fu_342_p1;

assign buffer_c3_9_ce0 = buffer_c3_9_ce0_local;

assign buffer_c3_address0 = zext_ln116_fu_342_p1;

assign buffer_c3_ce0 = buffer_c3_ce0_local;

assign empty_fu_328_p3 = ((icmp_ln117_fu_314_p2[0:0] == 1'b1) ? 5'd1 : 5'd0);

assign flatten_address0 = zext_ln119_1_fu_469_p1;

assign flatten_ce0 = flatten_ce0_local;

assign flatten_d0 = tmp_s_reg_568;

assign flatten_we0 = flatten_we0_local;

assign icmp_ln116_fu_291_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 8'd192) ? 1'b1 : 1'b0);

assign icmp_ln117_fu_314_p2 = ((j_fu_92 == 4'd12) ? 1'b1 : 1'b0);

assign p_shl_fu_362_p3 = {{trunc_ln119_fu_358_p1}, {4'd0}};

assign select_ln116_fu_320_p3 = ((icmp_ln117_fu_314_p2[0:0] == 1'b1) ? 4'd0 : j_fu_92);

assign sub_ln119_fu_382_p2 = (p_shl_fu_362_p3 - zext_ln119_fu_378_p1);

assign tmp_fu_370_p3 = {{add_ln116_1_fu_336_p2}, {2'd0}};

assign tmp_s_fu_414_p25 = 'bx;

assign trunc_ln119_fu_358_p1 = add_ln116_1_fu_336_p2[3:0];

assign zext_ln116_fu_342_p1 = add_ln116_1_fu_336_p2;

assign zext_ln117_fu_388_p1 = select_ln116_fu_320_p3;

assign zext_ln119_1_fu_469_p1 = add_ln119_reg_563_pp0_iter2_reg;

assign zext_ln119_fu_378_p1 = tmp_fu_370_p3;

endmodule //tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_116_12_VITIS_LOOP_117_13
