-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_121_9_VITIS_LOOP_122_10_p_ZL12conv3_weLf8 is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_121_9_VITIS_LOOP_122_10_p_ZL12conv3_weLf8 is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00001010", 1 => "00010001", 2 => "00000110", 3 => "00000010", 
    4 => "10010101", 5 => "00010001", 6 => "00010001", 7 => "00011000", 
    8 => "10010000", 9 => "10111000", 10 => "11000011", 11 => "11011001", 
    12 => "01001000", 13 => "11011001", 14 => "01010110", 15 => "00010010", 
    16 => "00010110", 17 => "00111101", 18 => "01000010", 19 => "10101010", 
    20 => "01111111", 21 => "00001100", 22 => "00000001", 23 => "11110101", 
    24 => "11000011", 25 => "11111100", 26 => "00101010", 27 => "11001100", 
    28 => "11101100", 29 => "00010001", 30 => "11010000", 31 => "00010000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;

end if;
end process;

end rtl;

