"""export_weights_to_cpp.py: Extracts INT8 quantized weights from the QAT model
and writes them into a static C header file (weights.h) for FPGA/HLS synthesis.

Loads the 92.46% QAT checkpoint, extracts INT8 weights via .int_repr().numpy().flatten(),
and formats all tensors as flattened 1D C-style arrays with quantization metadata.
"""

import os
import torch
import numpy as np
from model_cnn import TinyECG_CNN


def load_quantized_model(model_path):
    """Reconstruct the quantized model with the exact QAT pipeline and load weights."""
    backend = torch.backends.quantized.supported_engines[0]
    torch.backends.quantized.engine = backend

    model = TinyECG_CNN()
    model.train()
    model.fuse_model()
    model.qconfig = torch.ao.quantization.get_default_qat_qconfig(backend)
    torch.ao.quantization.prepare_qat(model, inplace=True)
    model.eval()
    torch.ao.quantization.convert(model, inplace=True)
    model.load_state_dict(torch.load(model_path, weights_only=True))
    model.eval()

    return model


def format_int_array(name, data, dtype="int8_t", per_line=16):
    """Format a numpy array as a C const array definition."""
    values = data.flatten().tolist()
    lines = [f"const {dtype} {name}[{len(values)}] = {{"]
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        val_str = ", ".join(f"{int(v):>4d}" for v in chunk)
        comma = "," if i + per_line < len(values) else ""
        lines.append(f"    {val_str}{comma}")
    lines.append("};")
    return "\n".join(lines)


def format_float_array(name, data, per_line=8):
    """Format a float array as a C const array definition."""
    values = data.flatten().tolist()
    lines = [f"const float {name}[{len(values)}] = {{"]
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        val_str = ", ".join(f"{v:.10f}f" for v in chunk)
        comma = "," if i + per_line < len(values) else ""
        lines.append(f"    {val_str}{comma}")
    lines.append("};")
    return "\n".join(lines)


def export_weights():
    print("=" * 60)
    print("  Export INT8 Weights to C Header (weights.h)")
    print("=" * 60)

    model_path = "saved_models/tiny_ecg_qat.pth"
    if not os.path.exists(model_path):
        print(f"[ERROR] Model not found: {model_path}")
        return

    print(f"\nLoading quantized model from: {model_path}")
    model = load_quantized_model(model_path)
    print("Model loaded successfully.\n")

    # --- Collect input scale from QuantStub ---
    quant_scale = model.quant.scale
    quant_zp = model.quant.zero_point
    if isinstance(quant_scale, torch.Tensor):
        quant_scale = quant_scale.item()
    if isinstance(quant_zp, torch.Tensor):
        quant_zp = quant_zp.item()

    # --- Layer definitions ---
    layer_info = [
        ("conv1", model.conv1, "Conv1d(1->8, k=5, s=2, p=2)", "90->45"),
        ("conv2", model.conv2, "Conv1d(8->16, k=5, s=2, p=2)", "45->23"),
        ("conv3", model.conv3, "Conv1d(16->16, k=3, s=2, p=1)", "23->12"),
        ("fc",    model.fc,    "Linear(192->2)",                 "192->2"),
    ]

    # Determine input scale for each layer (needed for bias quantization to INT32)
    # Layer N's input scale = Layer (N-1)'s output scale
    input_scales = [quant_scale]  # conv1 gets QuantStub scale
    for _, layer, _, _ in layer_info[:-1]:  # conv1, conv2, conv3
        input_scales.append(layer.scale)    # output scale becomes next layer's input

    # --- Build header ---
    H = []
    H.append("/*")
    H.append(" * weights.h - Static INT8 weights for TinyECG_CNN v3")
    H.append(" * Auto-generated by export_weights_to_cpp.py")
    H.append(" * Model: QAT v3 (92.46% accuracy, 73.91% sensitivity on DS2)")
    H.append(" * Target: Lattice iCE40 FPGA (15 KB BRAM budget)")
    H.append(" *")
    H.append(" * Architecture:")
    H.append(" *   Conv1: 1->8 ch,  kernel=5, stride=2, pad=2  (90->45)")
    H.append(" *   Conv2: 8->16 ch, kernel=5, stride=2, pad=2  (45->23)")
    H.append(" *   Conv3: 16->16 ch, kernel=3, stride=2, pad=1 (23->12)")
    H.append(" *   FC:    192->2 (binary classification)")
    H.append(" *")
    H.append(" * Weights: int8_t  (per-channel quantized)")
    H.append(" * Biases:  int32_t (quantized for INT8 accumulation)")
    H.append(" */")
    H.append("")
    H.append("#ifndef WEIGHTS_H")
    H.append("#define WEIGHTS_H")
    H.append("")
    H.append("#include <stdint.h>")
    H.append("")

    total_weight_bytes = 0
    total_bias_bytes = 0

    for idx, (name, layer, desc, dim_change) in enumerate(layer_info):
        print(f"[{name}] {desc}  ({dim_change})")

        # --- Extract INT8 weights ---
        qweight = layer.weight()
        int8_weights = qweight.int_repr().numpy().flatten()

        # Verify strict INT8 range [-128, 127]
        w_min, w_max = int(int8_weights.min()), int(int8_weights.max())
        assert -128 <= w_min and w_max <= 127, \
            f"{name} weights out of INT8 range: [{w_min}, {w_max}]"
        print(f"  Weights: shape={list(qweight.int_repr().shape)}, "
              f"count={len(int8_weights)}, range=[{w_min}, {w_max}] OK")

        # --- Extract quantization scales/zero-points ---
        if qweight.qscheme() in (torch.per_channel_affine, torch.per_channel_symmetric):
            w_scales = qweight.q_per_channel_scales().numpy()
            w_zps = qweight.q_per_channel_zero_points().numpy()
            print(f"  Quantization: per-channel, {len(w_scales)} channels")
        else:
            w_scales = np.array([qweight.q_scale()])
            w_zps = np.array([qweight.q_zero_point()])
            print(f"  Quantization: per-tensor, scale={w_scales[0]:.8f}")

        # --- Extract and quantize bias to INT32 ---
        bias_fp32 = layer.bias().detach().numpy().flatten()
        inp_scale = input_scales[idx]

        # Quantize bias: bias_int32[c] = round(bias_fp32[c] / (input_scale * weight_scale[c]))
        bias_int32 = np.zeros(len(bias_fp32), dtype=np.int32)
        for c in range(len(bias_fp32)):
            scale_c = w_scales[c] if len(w_scales) > 1 else w_scales[0]
            combined_scale = inp_scale * scale_c
            if combined_scale > 0:
                bias_int32[c] = int(np.round(bias_fp32[c] / combined_scale))
            else:
                bias_int32[c] = 0
        print(f"  Bias (fp32):  [{', '.join(f'{b:.4f}' for b in bias_fp32)}]")
        print(f"  Bias (int32): [{', '.join(str(b) for b in bias_int32)}]")

        # --- Output activation scale/zero-point ---
        if hasattr(layer, 'scale'):
            out_scale = layer.scale
            out_zp = layer.zero_point
            print(f"  Output: scale={out_scale:.8f}, zero_point={out_zp}")
        print()

        total_weight_bytes += len(int8_weights)
        total_bias_bytes += len(bias_int32) * 4  # int32 = 4 bytes

        # --- Write to header ---
        H.append(f"/* ---- {name}: {desc} ({dim_change}) ---- */")
        H.append(f"/* Weight shape: {list(qweight.int_repr().shape)}, "
                 f"range: [{w_min}, {w_max}] */")
        H.append(format_int_array(f"{name}_weight", int8_weights, "int8_t"))
        H.append("")
        H.append(f"/* Bias: quantized to INT32 for accumulation precision */")
        H.append(format_int_array(f"{name}_bias", bias_int32, "int32_t", per_line=8))
        H.append("")
        H.append(f"/* Per-channel weight scales ({len(w_scales)} channels) */")
        H.append(format_float_array(f"{name}_weight_scale", w_scales))
        H.append("")
        if hasattr(layer, 'scale'):
            H.append(f"const float {name}_output_scale = {layer.scale:.10f}f;")
            H.append(f"const int8_t {name}_output_zp = {int(layer.zero_point)};")
            H.append("")
        H.append("")

    # --- Input quantization from QuantStub ---
    H.append("/* ---- Input Quantization (QuantStub) ---- */")
    H.append(f"const float input_scale = {quant_scale:.10f}f;")
    H.append(f"const int8_t input_zero_point = {int(quant_zp)};")
    H.append("")

    # --- Layer configuration constants ---
    H.append("/* ---- Layer Configuration ---- */")
    H.append("const int CONV1_IN_CH = 1,  CONV1_OUT_CH = 8,  CONV1_KERNEL = 5, CONV1_STRIDE = 2, CONV1_PAD = 2;")
    H.append("const int CONV2_IN_CH = 8,  CONV2_OUT_CH = 16, CONV2_KERNEL = 5, CONV2_STRIDE = 2, CONV2_PAD = 2;")
    H.append("const int CONV3_IN_CH = 16, CONV3_OUT_CH = 16, CONV3_KERNEL = 3, CONV3_STRIDE = 2, CONV3_PAD = 1;")
    H.append("const int FC_IN = 192, FC_OUT = 2;")
    H.append("const int INPUT_LENGTH = 90;")
    H.append("")
    H.append("#endif /* WEIGHTS_H */")
    H.append("")

    # --- Write the file ---
    output_path = "weights.h"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(H))

    file_size = os.path.getsize(output_path)
    print("=" * 60)
    print("  EXPORT COMPLETE")
    print("=" * 60)
    print(f"  Output file:   {output_path} ({file_size:,} bytes)")
    print(f"  Weight data:   {total_weight_bytes:,} bytes (INT8)")
    print(f"  Bias data:     {total_bias_bytes:,} bytes (INT32)")
    print(f"  Total model:   {(total_weight_bytes + total_bias_bytes):,} bytes "
          f"({(total_weight_bytes + total_bias_bytes) / 1024:.2f} KB)")
    print(f"  BRAM usage:    {(total_weight_bytes + total_bias_bytes) / (15 * 1024) * 100:.1f}% "
          f"of 15 KB limit")
    print()
    print("  All weights verified in [-128, 127] range. READY FOR HLS.")
    print("=" * 60)


if __name__ == "__main__":
    export_weights()
