-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_113_8_VITIS_LOOP_114_9_p_ZL12conv3_weiLf8 is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_113_8_VITIS_LOOP_114_9_p_ZL12conv3_weiLf8 is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00001100", 1 => "11010101", 2 => "00010110", 3 => "11100100", 
    4 => "10110111", 5 => "11100111", 6 => "11100000", 7 => "00001010", 
    8 => "11111101", 9 => "00010001", 10 => "11110010", 11 => "11111111", 
    12 => "01011110", 13 => "01111110", 14 => "10110000", 15 => "01011000", 
    16 => "01110101", 17 => "00011010", 18 => "10010010", 19 => "11101000", 
    20 => "01000011", 21 => "00010000", 22 => "00111111", 23 => "11110110", 
    24 => "00110101", 25 => "00001000", 26 => "01011000", 27 => "00111101", 
    28 => "00011110", 29 => "00111000", 30 => "11111110", 31 => "11100110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;

end if;
end process;

end rtl;

