# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ecg_zynq_bd/ecg_zynq_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_zynq_bd || ORIG_REF_NAME==ecg_zynq_bd} -quiet] -quiet

# IP: bd/ecg_zynq_bd/ip/ecg_zynq_bd_processing_system7_0_0_4/ecg_zynq_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_zynq_bd_processing_system7_0_0 || ORIG_REF_NAME==ecg_zynq_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/ecg_zynq_bd/ip/ecg_zynq_bd_tiny_ecg_inference_0_0_4/ecg_zynq_bd_tiny_ecg_inference_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_zynq_bd_tiny_ecg_inference_0_0 || ORIG_REF_NAME==ecg_zynq_bd_tiny_ecg_inference_0_0} -quiet] -quiet

# IP: bd/ecg_zynq_bd/ip/ecg_zynq_bd_axi_interconnect_0_imp_auto_pc_0_4/ecg_zynq_bd_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_zynq_bd_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==ecg_zynq_bd_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# IP: bd/ecg_zynq_bd/ip/ecg_zynq_bd_axi_interconnect_0_0_4/ecg_zynq_bd_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_zynq_bd_axi_interconnect_0_0 || ORIG_REF_NAME==ecg_zynq_bd_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/ecg_zynq_bd/ip/ecg_zynq_bd_axi_interconnect_1_imp_xbar_0_4/ecg_zynq_bd_axi_interconnect_1_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_zynq_bd_axi_interconnect_1_imp_xbar_0 || ORIG_REF_NAME==ecg_zynq_bd_axi_interconnect_1_imp_xbar_0} -quiet] -quiet

# IP: bd/ecg_zynq_bd/ip/ecg_zynq_bd_axi_interconnect_1_imp_auto_pc_0_4/ecg_zynq_bd_axi_interconnect_1_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_zynq_bd_axi_interconnect_1_imp_auto_pc_0 || ORIG_REF_NAME==ecg_zynq_bd_axi_interconnect_1_imp_auto_pc_0} -quiet] -quiet

# IP: bd/ecg_zynq_bd/ip/ecg_zynq_bd_axi_interconnect_1_imp_auto_us_0_4/ecg_zynq_bd_axi_interconnect_1_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_zynq_bd_axi_interconnect_1_imp_auto_us_0 || ORIG_REF_NAME==ecg_zynq_bd_axi_interconnect_1_imp_auto_us_0} -quiet] -quiet

# IP: bd/ecg_zynq_bd/ip/ecg_zynq_bd_axi_interconnect_1_imp_auto_pc_1_4/ecg_zynq_bd_axi_interconnect_1_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_zynq_bd_axi_interconnect_1_imp_auto_pc_1 || ORIG_REF_NAME==ecg_zynq_bd_axi_interconnect_1_imp_auto_pc_1} -quiet] -quiet

# IP: bd/ecg_zynq_bd/ip/ecg_zynq_bd_axi_interconnect_1_imp_auto_us_1_4/ecg_zynq_bd_axi_interconnect_1_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_zynq_bd_axi_interconnect_1_imp_auto_us_1 || ORIG_REF_NAME==ecg_zynq_bd_axi_interconnect_1_imp_auto_us_1} -quiet] -quiet

# IP: bd/ecg_zynq_bd/ip/ecg_zynq_bd_axi_interconnect_1_0_4/ecg_zynq_bd_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_zynq_bd_axi_interconnect_1_0 || ORIG_REF_NAME==ecg_zynq_bd_axi_interconnect_1_0} -quiet] -quiet

# XDC: /home/vishal/vishal_dev/EB_caps/ECG-Arrhythmia_Detection-ES/Wearable_ECG_EdgeAI/ecg_hw_project/ecg_hw_project.gen/sources_1/bd/ecg_zynq_bd/ip/ecg_zynq_bd_processing_system7_0_0_4/ecg_zynq_bd_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ecg_zynq_bd_processing_system7_0_0 || ORIG_REF_NAME==ecg_zynq_bd_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vishal/vishal_dev/EB_caps/ECG-Arrhythmia_Detection-ES/Wearable_ECG_EdgeAI/ecg_hw_project/ecg_hw_project.gen/sources_1/bd/ecg_zynq_bd/ip/ecg_zynq_bd_tiny_ecg_inference_0_0_4/constraints/tiny_ecg_inference_ooc.xdc

# XDC: /home/vishal/vishal_dev/EB_caps/ECG-Arrhythmia_Detection-ES/Wearable_ECG_EdgeAI/ecg_hw_project/ecg_hw_project.gen/sources_1/bd/ecg_zynq_bd/ip/ecg_zynq_bd_axi_interconnect_0_imp_auto_pc_0_4/ecg_zynq_bd_axi_interconnect_0_imp_auto_pc_0_ooc.xdc

# XDC: /home/vishal/vishal_dev/EB_caps/ECG-Arrhythmia_Detection-ES/Wearable_ECG_EdgeAI/ecg_hw_project/ecg_hw_project.gen/sources_1/bd/ecg_zynq_bd/ip/ecg_zynq_bd_axi_interconnect_1_imp_auto_pc_0_4/ecg_zynq_bd_axi_interconnect_1_imp_auto_pc_0_ooc.xdc

# XDC: /home/vishal/vishal_dev/EB_caps/ECG-Arrhythmia_Detection-ES/Wearable_ECG_EdgeAI/ecg_hw_project/ecg_hw_project.gen/sources_1/bd/ecg_zynq_bd/ip/ecg_zynq_bd_axi_interconnect_1_imp_auto_us_0_4/ecg_zynq_bd_axi_interconnect_1_imp_auto_us_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ecg_zynq_bd_axi_interconnect_1_imp_auto_us_0 || ORIG_REF_NAME==ecg_zynq_bd_axi_interconnect_1_imp_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vishal/vishal_dev/EB_caps/ECG-Arrhythmia_Detection-ES/Wearable_ECG_EdgeAI/ecg_hw_project/ecg_hw_project.gen/sources_1/bd/ecg_zynq_bd/ip/ecg_zynq_bd_axi_interconnect_1_imp_auto_us_0_4/ecg_zynq_bd_axi_interconnect_1_imp_auto_us_0_ooc.xdc

# XDC: /home/vishal/vishal_dev/EB_caps/ECG-Arrhythmia_Detection-ES/Wearable_ECG_EdgeAI/ecg_hw_project/ecg_hw_project.gen/sources_1/bd/ecg_zynq_bd/ip/ecg_zynq_bd_axi_interconnect_1_imp_auto_pc_1_4/ecg_zynq_bd_axi_interconnect_1_imp_auto_pc_1_ooc.xdc

# XDC: /home/vishal/vishal_dev/EB_caps/ECG-Arrhythmia_Detection-ES/Wearable_ECG_EdgeAI/ecg_hw_project/ecg_hw_project.gen/sources_1/bd/ecg_zynq_bd/ip/ecg_zynq_bd_axi_interconnect_1_imp_auto_us_1_4/ecg_zynq_bd_axi_interconnect_1_imp_auto_us_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ecg_zynq_bd_axi_interconnect_1_imp_auto_us_1 || ORIG_REF_NAME==ecg_zynq_bd_axi_interconnect_1_imp_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vishal/vishal_dev/EB_caps/ECG-Arrhythmia_Detection-ES/Wearable_ECG_EdgeAI/ecg_hw_project/ecg_hw_project.gen/sources_1/bd/ecg_zynq_bd/ip/ecg_zynq_bd_axi_interconnect_1_imp_auto_us_1_4/ecg_zynq_bd_axi_interconnect_1_imp_auto_us_1_ooc.xdc

# XDC: /home/vishal/vishal_dev/EB_caps/ECG-Arrhythmia_Detection-ES/Wearable_ECG_EdgeAI/ecg_hw_project/ecg_hw_project.gen/sources_1/bd/ecg_zynq_bd/ecg_zynq_bd_ooc.xdc
