[hls]
relative_roots=/home/vishal/vishal_dev/EB_caps/ECG-Arrhythmia_Detection-ES/Wearable_ECG_EdgeAI
# Inferred from syn.array_partition.complete_threshold=4
syn.directive.array_partition=tiny_ecg_inference/fc_bias dim=1 type=complete variable=fc_bias
# Inferred from performance & pipeline pragmas/directives
syn.directive.array_partition=tiny_ecg_inference/conv1_weight dim=1 type=cyclic factor=5 variable=conv1_weight
syn.directive.array_partition=tiny_ecg_inference/conv2_weight dim=1 type=cyclic factor=20 variable=conv2_weight
syn.directive.array_partition=tiny_ecg_inference/conv3_weight dim=1 type=cyclic factor=24 variable=conv3_weight
syn.directive.array_partition=tiny_ecg_inference/buffer_c3 dim=2 type=complete variable=buffer_c3
syn.directive.loop_flatten=tiny_ecg_inference/VITIS_LOOP_117_13  
syn.directive.array_partition=tiny_ecg_inference/fc_weight dim=1 type=complete variable=fc_weight


