set ModuleHierarchy {[{
"Name" : "tiny_ecg_inference", "RefName" : "tiny_ecg_inference","ID" : "0","Type" : "sequential",
"SubInsts" : [
	{"Name" : "grp_tiny_ecg_inference_Pipeline_VITIS_LOOP_33_1_fu_5101", "RefName" : "tiny_ecg_inference_Pipeline_VITIS_LOOP_33_1","ID" : "1","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "VITIS_LOOP_33_1","RefName" : "VITIS_LOOP_33_1","ID" : "2","Type" : "pipeline",
		"SubInsts" : [
		{"Name" : "buffer_c1_relu_i8_fu_5540", "RefName" : "relu_i8","ID" : "3","Type" : "pipeline"},
		{"Name" : "buffer_c1_44_relu_i8_fu_5545", "RefName" : "relu_i8","ID" : "4","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "5","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "6","Type" : "pipeline"},
		{"Name" : "buffer_c1_3_relu_i8_fu_5560", "RefName" : "relu_i8","ID" : "7","Type" : "pipeline"},
		{"Name" : "buffer_c1_4_relu_i8_fu_5565", "RefName" : "relu_i8","ID" : "8","Type" : "pipeline"},
		{"Name" : "buffer_c1_5_relu_i8_fu_5570", "RefName" : "relu_i8","ID" : "9","Type" : "pipeline"},
		{"Name" : "buffer_c1_6_relu_i8_fu_5575", "RefName" : "relu_i8","ID" : "10","Type" : "pipeline"},
		{"Name" : "buffer_c1_7_relu_i8_fu_5580", "RefName" : "relu_i8","ID" : "11","Type" : "pipeline"},
		{"Name" : "buffer_c1_8_relu_i8_fu_5585", "RefName" : "relu_i8","ID" : "12","Type" : "pipeline"},
		{"Name" : "buffer_c1_9_relu_i8_fu_5590", "RefName" : "relu_i8","ID" : "13","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "14","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "15","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "16","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "17","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "18","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "19","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "20","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "21","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "22","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "23","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "24","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "25","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "26","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "27","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "28","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "29","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "30","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "31","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "32","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "33","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "34","Type" : "pipeline"},
		{"Name" : "buffer_c1_31_relu_i8_fu_5700", "RefName" : "relu_i8","ID" : "35","Type" : "pipeline"},
		{"Name" : "buffer_c1_32_relu_i8_fu_5705", "RefName" : "relu_i8","ID" : "36","Type" : "pipeline"},
		{"Name" : "buffer_c1_33_relu_i8_fu_5710", "RefName" : "relu_i8","ID" : "37","Type" : "pipeline"},
		{"Name" : "buffer_c1_34_relu_i8_fu_5715", "RefName" : "relu_i8","ID" : "38","Type" : "pipeline"},
		{"Name" : "buffer_c1_35_relu_i8_fu_5720", "RefName" : "relu_i8","ID" : "39","Type" : "pipeline"},
		{"Name" : "buffer_c1_36_relu_i8_fu_5725", "RefName" : "relu_i8","ID" : "40","Type" : "pipeline"},
		{"Name" : "buffer_c1_37_relu_i8_fu_5730", "RefName" : "relu_i8","ID" : "41","Type" : "pipeline"},
		{"Name" : "buffer_c1_38_relu_i8_fu_5735", "RefName" : "relu_i8","ID" : "42","Type" : "pipeline"},
		{"Name" : "buffer_c1_39_relu_i8_fu_5740", "RefName" : "relu_i8","ID" : "43","Type" : "pipeline"},
		{"Name" : "buffer_c1_40_relu_i8_fu_5745", "RefName" : "relu_i8","ID" : "44","Type" : "pipeline"},
		{"Name" : "buffer_c1_41_relu_i8_fu_5750", "RefName" : "relu_i8","ID" : "45","Type" : "pipeline"},
		{"Name" : "buffer_c1_42_relu_i8_fu_5755", "RefName" : "relu_i8","ID" : "46","Type" : "pipeline"},
		{"Name" : "buffer_c1_43_relu_i8_fu_5760", "RefName" : "relu_i8","ID" : "47","Type" : "pipeline"},]},]},
	{"Name" : "grp_tiny_ecg_inference_Pipeline_VITIS_LOOP_59_4_fu_5568", "RefName" : "tiny_ecg_inference_Pipeline_VITIS_LOOP_59_4","ID" : "48","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "VITIS_LOOP_59_4","RefName" : "VITIS_LOOP_59_4","ID" : "49","Type" : "pipeline",
		"SubInsts" : [
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "50","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "51","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "52","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "53","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "54","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "55","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "56","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "57","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "58","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "59","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "60","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "61","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "62","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "63","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "64","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "65","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "66","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "67","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "68","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "69","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "70","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "71","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "72","Type" : "pipeline"},]},]},
	{"Name" : "grp_tiny_ecg_inference_Pipeline_VITIS_LOOP_88_8_fu_6342", "RefName" : "tiny_ecg_inference_Pipeline_VITIS_LOOP_88_8","ID" : "73","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "VITIS_LOOP_88_8","RefName" : "VITIS_LOOP_88_8","ID" : "74","Type" : "pipeline",
		"SubInsts" : [
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "75","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "76","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "77","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "78","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "79","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "80","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "81","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "82","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "83","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "84","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "85","Type" : "pipeline"},
		{"Name" : "relu_i8", "RefName" : "relu_i8","ID" : "86","Type" : "pipeline"},]},]},
	{"Name" : "grp_tiny_ecg_inference_Pipeline_VITIS_LOOP_116_12_VITIS_LOOP_117_13_fu_6776", "RefName" : "tiny_ecg_inference_Pipeline_VITIS_LOOP_116_12_VITIS_LOOP_117_13","ID" : "87","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "VITIS_LOOP_116_12_VITIS_LOOP_117_13","RefName" : "VITIS_LOOP_116_12_VITIS_LOOP_117_13","ID" : "88","Type" : "pipeline"},]},
	{"Name" : "grp_tiny_ecg_inference_Pipeline_VITIS_LOOP_126_14_fu_6793", "RefName" : "tiny_ecg_inference_Pipeline_VITIS_LOOP_126_14","ID" : "89","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "VITIS_LOOP_126_14","RefName" : "VITIS_LOOP_126_14","ID" : "90","Type" : "pipeline"},]},]
}]}