// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module tiny_ecg_inference_relu_i8 (
        ap_ready,
        value_r,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [20:0] value_r;
output  [6:0] ap_return;
input   ap_rst;

wire   [13:0] tmp_11_fu_34_p4;
wire   [0:0] tmp_fu_26_p3;
wire   [0:0] xor_ln11_fu_54_p2;
wire   [0:0] icmp_ln5_fu_44_p2;
wire   [0:0] or_ln11_fu_68_p2;
wire   [6:0] select_ln11_1_fu_60_p3;
wire   [6:0] trunc_ln7_fu_50_p1;

assign ap_ready = 1'b1;

assign or_ln11_fu_68_p2 = (tmp_fu_26_p3 | icmp_ln5_fu_44_p2);

assign select_ln11_1_fu_60_p3 = ((xor_ln11_fu_54_p2[0:0] == 1'b1) ? 7'd127 : 7'd0);

assign tmp_11_fu_34_p4 = {{value_r[20:7]}};

assign tmp_fu_26_p3 = value_r[32'd20];

assign trunc_ln7_fu_50_p1 = value_r[6:0];

assign xor_ln11_fu_54_p2 = (tmp_fu_26_p3 ^ 1'd1);

assign ap_return = ((or_ln11_fu_68_p2[0:0] == 1'b1) ? select_ln11_1_fu_60_p3 : trunc_ln7_fu_50_p1);

assign icmp_ln5_fu_44_p2 = (($signed(tmp_11_fu_34_p4) > $signed(14'd0)) ? 1'b1 : 1'b0);

endmodule //tiny_ecg_inference_relu_i8
