set_property PACKAGE_PIN U10 [get_ports {oled_pins_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oled_pins_tri_o[0]}]
set_property PACKAGE_PIN U9 [get_ports {oled_pins_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oled_pins_tri_o[1]}]
set_property PACKAGE_PIN AB12 [get_ports {oled_pins_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oled_pins_tri_o[2]}]
set_property PACKAGE_PIN AA12 [get_ports {oled_pins_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oled_pins_tri_o[3]}]
set_property PACKAGE_PIN U11 [get_ports {oled_pins_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oled_pins_tri_o[4]}]
set_property PACKAGE_PIN U12 [get_ports {oled_pins_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oled_pins_tri_o[5]}]

set_property PACKAGE_PIN Y11 [get_ports {buzzer_pin_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buzzer_pin_tri_o[0]}]
