-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2026.1 (win64) Build 6511674 Tue Jun 16 11:02:23 MDT 2026
-- Date        : Fri Sep  4 10:28:57 2026
-- Host        : Devadharshan running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_1_tiny_ecg_inference_0_0_stub.vhdl
-- Design      : design_1_tiny_ecg_inference_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7z020clg484-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    s_axi_CTRL_ARADDR : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_CTRL_ARREADY : out STD_LOGIC;
    s_axi_CTRL_ARVALID : in STD_LOGIC;
    s_axi_CTRL_AWADDR : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_CTRL_AWREADY : out STD_LOGIC;
    s_axi_CTRL_AWVALID : in STD_LOGIC;
    s_axi_CTRL_BREADY : in STD_LOGIC;
    s_axi_CTRL_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_CTRL_BVALID : out STD_LOGIC;
    s_axi_CTRL_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_CTRL_RREADY : in STD_LOGIC;
    s_axi_CTRL_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_CTRL_RVALID : out STD_LOGIC;
    s_axi_CTRL_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_CTRL_WREADY : out STD_LOGIC;
    s_axi_CTRL_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_CTRL_WVALID : in STD_LOGIC;
    s_axi_control_ARADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_control_ARREADY : out STD_LOGIC;
    s_axi_control_ARVALID : in STD_LOGIC;
    s_axi_control_AWADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_control_AWREADY : out STD_LOGIC;
    s_axi_control_AWVALID : in STD_LOGIC;
    s_axi_control_BREADY : in STD_LOGIC;
    s_axi_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_BVALID : out STD_LOGIC;
    s_axi_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_RREADY : in STD_LOGIC;
    s_axi_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_RVALID : out STD_LOGIC;
    s_axi_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_WREADY : out STD_LOGIC;
    s_axi_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_WVALID : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_DATA_IN_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_DATA_IN_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_IN_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_IN_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_DATA_IN_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_DATA_IN_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_IN_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_IN_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_IN_ARREADY : in STD_LOGIC;
    m_axi_DATA_IN_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_IN_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_IN_ARVALID : out STD_LOGIC;
    m_axi_DATA_IN_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_DATA_IN_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_IN_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_IN_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_DATA_IN_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_DATA_IN_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_IN_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_IN_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_IN_AWREADY : in STD_LOGIC;
    m_axi_DATA_IN_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_IN_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_IN_AWVALID : out STD_LOGIC;
    m_axi_DATA_IN_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_DATA_IN_BREADY : out STD_LOGIC;
    m_axi_DATA_IN_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_IN_BVALID : in STD_LOGIC;
    m_axi_DATA_IN_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_IN_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_DATA_IN_RLAST : in STD_LOGIC;
    m_axi_DATA_IN_RREADY : out STD_LOGIC;
    m_axi_DATA_IN_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_IN_RVALID : in STD_LOGIC;
    m_axi_DATA_IN_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_IN_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_DATA_IN_WLAST : out STD_LOGIC;
    m_axi_DATA_IN_WREADY : in STD_LOGIC;
    m_axi_DATA_IN_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_IN_WVALID : out STD_LOGIC;
    m_axi_DATA_OUT_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_DATA_OUT_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_OUT_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_OUT_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_DATA_OUT_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_DATA_OUT_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_OUT_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_OUT_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_OUT_ARREADY : in STD_LOGIC;
    m_axi_DATA_OUT_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_OUT_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_OUT_ARVALID : out STD_LOGIC;
    m_axi_DATA_OUT_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_DATA_OUT_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_OUT_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_OUT_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_DATA_OUT_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_DATA_OUT_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_OUT_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_OUT_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_OUT_AWREADY : in STD_LOGIC;
    m_axi_DATA_OUT_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_OUT_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_OUT_AWVALID : out STD_LOGIC;
    m_axi_DATA_OUT_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_DATA_OUT_BREADY : out STD_LOGIC;
    m_axi_DATA_OUT_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_OUT_BVALID : in STD_LOGIC;
    m_axi_DATA_OUT_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_OUT_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_DATA_OUT_RLAST : in STD_LOGIC;
    m_axi_DATA_OUT_RREADY : out STD_LOGIC;
    m_axi_DATA_OUT_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_OUT_RVALID : in STD_LOGIC;
    m_axi_DATA_OUT_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_OUT_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_DATA_OUT_WLAST : out STD_LOGIC;
    m_axi_DATA_OUT_WREADY : in STD_LOGIC;
    m_axi_DATA_OUT_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_OUT_WVALID : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "design_1_tiny_ecg_inference_0_0,tiny_ecg_inference,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "design_1_tiny_ecg_inference_0_0,tiny_ecg_inference,{x_ipProduct=Vivado 2026.1,x_ipVendor=xilinx.com,x_ipLibrary=hls,x_ipName=tiny_ecg_inference,x_ipVersion=1.0,x_ipCoreRevision=2114771047,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_S_AXI_CTRL_ADDR_WIDTH=4,C_S_AXI_CTRL_DATA_WIDTH=32,C_S_AXI_CONTROL_ADDR_WIDTH=6,C_S_AXI_CONTROL_DATA_WIDTH=32,C_M_AXI_DATA_IN_ID_WIDTH=1,C_M_AXI_DATA_IN_ADDR_WIDTH=64,C_M_AXI_DATA_IN_DATA_WIDTH=32,C_M_AXI_DATA_IN_AWUSER_WIDTH=1,C_M_AXI_DATA_IN_ARUSER_WIDTH=1,C_M_AXI_DATA_IN_WUSER_WIDTH=1,C_M_AXI_DATA_IN_RUSER_WIDTH=1,C_M_AXI_DATA_IN_BUSER_WIDTH=1,C_M_AXI_DATA_IN_USER_VALUE=0x00000000,C_M_AXI_DATA_IN_PROT_VALUE=000,C_M_AXI_DATA_IN_CACHE_VALUE=0011,C_M_AXI_DATA_OUT_ID_WIDTH=1,C_M_AXI_DATA_OUT_ADDR_WIDTH=64,C_M_AXI_DATA_OUT_DATA_WIDTH=32,C_M_AXI_DATA_OUT_AWUSER_WIDTH=1,C_M_AXI_DATA_OUT_ARUSER_WIDTH=1,C_M_AXI_DATA_OUT_WUSER_WIDTH=1,C_M_AXI_DATA_OUT_RUSER_WIDTH=1,C_M_AXI_DATA_OUT_BUSER_WIDTH=1,C_M_AXI_DATA_OUT_USER_VALUE=0x00000000,C_M_AXI_DATA_OUT_PROT_VALUE=000,C_M_AXI_DATA_OUT_CACHE_VALUE=0011}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "HLS";
  attribute hls_module : string;
  attribute hls_module of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_CTRL_ARADDR[3:0],s_axi_CTRL_ARREADY,s_axi_CTRL_ARVALID,s_axi_CTRL_AWADDR[3:0],s_axi_CTRL_AWREADY,s_axi_CTRL_AWVALID,s_axi_CTRL_BREADY,s_axi_CTRL_BRESP[1:0],s_axi_CTRL_BVALID,s_axi_CTRL_RDATA[31:0],s_axi_CTRL_RREADY,s_axi_CTRL_RRESP[1:0],s_axi_CTRL_RVALID,s_axi_CTRL_WDATA[31:0],s_axi_CTRL_WREADY,s_axi_CTRL_WSTRB[3:0],s_axi_CTRL_WVALID,s_axi_control_ARADDR[5:0],s_axi_control_ARREADY,s_axi_control_ARVALID,s_axi_control_AWADDR[5:0],s_axi_control_AWREADY,s_axi_control_AWVALID,s_axi_control_BREADY,s_axi_control_BRESP[1:0],s_axi_control_BVALID,s_axi_control_RDATA[31:0],s_axi_control_RREADY,s_axi_control_RRESP[1:0],s_axi_control_RVALID,s_axi_control_WDATA[31:0],s_axi_control_WREADY,s_axi_control_WSTRB[3:0],s_axi_control_WVALID,ap_clk,ap_rst_n,interrupt,m_axi_DATA_IN_ARADDR[63:0],m_axi_DATA_IN_ARBURST[1:0],m_axi_DATA_IN_ARCACHE[3:0],m_axi_DATA_IN_ARID[0:0],m_axi_DATA_IN_ARLEN[7:0],m_axi_DATA_IN_ARLOCK[1:0],m_axi_DATA_IN_ARPROT[2:0],m_axi_DATA_IN_ARQOS[3:0],m_axi_DATA_IN_ARREADY,m_axi_DATA_IN_ARREGION[3:0],m_axi_DATA_IN_ARSIZE[2:0],m_axi_DATA_IN_ARVALID,m_axi_DATA_IN_AWADDR[63:0],m_axi_DATA_IN_AWBURST[1:0],m_axi_DATA_IN_AWCACHE[3:0],m_axi_DATA_IN_AWID[0:0],m_axi_DATA_IN_AWLEN[7:0],m_axi_DATA_IN_AWLOCK[1:0],m_axi_DATA_IN_AWPROT[2:0],m_axi_DATA_IN_AWQOS[3:0],m_axi_DATA_IN_AWREADY,m_axi_DATA_IN_AWREGION[3:0],m_axi_DATA_IN_AWSIZE[2:0],m_axi_DATA_IN_AWVALID,m_axi_DATA_IN_BID[0:0],m_axi_DATA_IN_BREADY,m_axi_DATA_IN_BRESP[1:0],m_axi_DATA_IN_BVALID,m_axi_DATA_IN_RDATA[31:0],m_axi_DATA_IN_RID[0:0],m_axi_DATA_IN_RLAST,m_axi_DATA_IN_RREADY,m_axi_DATA_IN_RRESP[1:0],m_axi_DATA_IN_RVALID,m_axi_DATA_IN_WDATA[31:0],m_axi_DATA_IN_WID[0:0],m_axi_DATA_IN_WLAST,m_axi_DATA_IN_WREADY,m_axi_DATA_IN_WSTRB[3:0],m_axi_DATA_IN_WVALID,m_axi_DATA_OUT_ARADDR[63:0],m_axi_DATA_OUT_ARBURST[1:0],m_axi_DATA_OUT_ARCACHE[3:0],m_axi_DATA_OUT_ARID[0:0],m_axi_DATA_OUT_ARLEN[7:0],m_axi_DATA_OUT_ARLOCK[1:0],m_axi_DATA_OUT_ARPROT[2:0],m_axi_DATA_OUT_ARQOS[3:0],m_axi_DATA_OUT_ARREADY,m_axi_DATA_OUT_ARREGION[3:0],m_axi_DATA_OUT_ARSIZE[2:0],m_axi_DATA_OUT_ARVALID,m_axi_DATA_OUT_AWADDR[63:0],m_axi_DATA_OUT_AWBURST[1:0],m_axi_DATA_OUT_AWCACHE[3:0],m_axi_DATA_OUT_AWID[0:0],m_axi_DATA_OUT_AWLEN[7:0],m_axi_DATA_OUT_AWLOCK[1:0],m_axi_DATA_OUT_AWPROT[2:0],m_axi_DATA_OUT_AWQOS[3:0],m_axi_DATA_OUT_AWREADY,m_axi_DATA_OUT_AWREGION[3:0],m_axi_DATA_OUT_AWSIZE[2:0],m_axi_DATA_OUT_AWVALID,m_axi_DATA_OUT_BID[0:0],m_axi_DATA_OUT_BREADY,m_axi_DATA_OUT_BRESP[1:0],m_axi_DATA_OUT_BVALID,m_axi_DATA_OUT_RDATA[31:0],m_axi_DATA_OUT_RID[0:0],m_axi_DATA_OUT_RLAST,m_axi_DATA_OUT_RREADY,m_axi_DATA_OUT_RRESP[1:0],m_axi_DATA_OUT_RVALID,m_axi_DATA_OUT_WDATA[31:0],m_axi_DATA_OUT_WID[0:0],m_axi_DATA_OUT_WLAST,m_axi_DATA_OUT_WREADY,m_axi_DATA_OUT_WSTRB[3:0],m_axi_DATA_OUT_WVALID";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_CTRL_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL ARADDR";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_CTRL_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_CTRL_ARADDR : signal is "XIL_INTERFACENAME s_axi_CTRL, ADDR_WIDTH 4, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 50000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_CTRL_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL ARREADY";
  attribute X_INTERFACE_INFO of s_axi_CTRL_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL ARVALID";
  attribute X_INTERFACE_INFO of s_axi_CTRL_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL AWADDR";
  attribute X_INTERFACE_INFO of s_axi_CTRL_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL AWREADY";
  attribute X_INTERFACE_INFO of s_axi_CTRL_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL AWVALID";
  attribute X_INTERFACE_INFO of s_axi_CTRL_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL BREADY";
  attribute X_INTERFACE_INFO of s_axi_CTRL_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL BRESP";
  attribute X_INTERFACE_INFO of s_axi_CTRL_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL BVALID";
  attribute X_INTERFACE_INFO of s_axi_CTRL_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL RDATA";
  attribute X_INTERFACE_INFO of s_axi_CTRL_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL RREADY";
  attribute X_INTERFACE_INFO of s_axi_CTRL_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL RRESP";
  attribute X_INTERFACE_INFO of s_axi_CTRL_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL RVALID";
  attribute X_INTERFACE_INFO of s_axi_CTRL_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL WDATA";
  attribute X_INTERFACE_INFO of s_axi_CTRL_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL WREADY";
  attribute X_INTERFACE_INFO of s_axi_CTRL_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL WSTRB";
  attribute X_INTERFACE_INFO of s_axi_CTRL_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL WVALID";
  attribute X_INTERFACE_INFO of s_axi_control_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARADDR";
  attribute X_INTERFACE_MODE of s_axi_control_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axi_control_ARADDR : signal is "XIL_INTERFACENAME s_axi_control, ADDR_WIDTH 6, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 50000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_control_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARREADY";
  attribute X_INTERFACE_INFO of s_axi_control_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARVALID";
  attribute X_INTERFACE_INFO of s_axi_control_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWADDR";
  attribute X_INTERFACE_INFO of s_axi_control_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWREADY";
  attribute X_INTERFACE_INFO of s_axi_control_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWVALID";
  attribute X_INTERFACE_INFO of s_axi_control_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BREADY";
  attribute X_INTERFACE_INFO of s_axi_control_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BRESP";
  attribute X_INTERFACE_INFO of s_axi_control_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BVALID";
  attribute X_INTERFACE_INFO of s_axi_control_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RDATA";
  attribute X_INTERFACE_INFO of s_axi_control_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RREADY";
  attribute X_INTERFACE_INFO of s_axi_control_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RRESP";
  attribute X_INTERFACE_INFO of s_axi_control_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RVALID";
  attribute X_INTERFACE_INFO of s_axi_control_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WDATA";
  attribute X_INTERFACE_INFO of s_axi_control_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WREADY";
  attribute X_INTERFACE_INFO of s_axi_control_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WSTRB";
  attribute X_INTERFACE_INFO of s_axi_control_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WVALID";
  attribute X_INTERFACE_INFO of ap_clk : signal is "xilinx.com:signal:clock:1.0 ap_clk CLK";
  attribute X_INTERFACE_MODE of ap_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_clk : signal is "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_CTRL:s_axi_control:m_axi_DATA_IN:m_axi_DATA_OUT, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 50000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ap_rst_n : signal is "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  attribute X_INTERFACE_MODE of ap_rst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_rst_n : signal is "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of interrupt : signal is "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  attribute X_INTERFACE_MODE of interrupt : signal is "master";
  attribute X_INTERFACE_PARAMETER of interrupt : signal is "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN ARADDR";
  attribute X_INTERFACE_MODE of m_axi_DATA_IN_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_DATA_IN_ARADDR : signal is "XIL_INTERFACENAME m_axi_DATA_IN, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 50000000, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN ARBURST";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN ARID";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN ARLEN";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN ARPROT";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN ARQOS";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN ARREADY";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN ARREGION";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN ARVALID";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN AWADDR";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN AWBURST";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN AWID";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN AWLEN";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN AWPROT";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN AWQOS";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN AWREADY";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN AWREGION";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN AWVALID";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN BID";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN BREADY";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN BRESP";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN BVALID";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN RDATA";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN RID";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN RLAST";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN RREADY";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN RRESP";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN RVALID";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN WDATA";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN WID";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN WLAST";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN WREADY";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN WSTRB";
  attribute X_INTERFACE_INFO of m_axi_DATA_IN_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_IN WVALID";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT ARADDR";
  attribute X_INTERFACE_MODE of m_axi_DATA_OUT_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_DATA_OUT_ARADDR : signal is "XIL_INTERFACENAME m_axi_DATA_OUT, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 50000000, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT ARBURST";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT ARID";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT ARLEN";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT ARPROT";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT ARQOS";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT ARREADY";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT ARREGION";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT ARVALID";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT AWADDR";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT AWBURST";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT AWID";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT AWLEN";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT AWPROT";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT AWQOS";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT AWREADY";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT AWREGION";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT AWVALID";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT BID";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT BREADY";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT BRESP";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT BVALID";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT RDATA";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT RID";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT RLAST";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT RREADY";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT RRESP";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT RVALID";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT WDATA";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT WID";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT WLAST";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT WREADY";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT WSTRB";
  attribute X_INTERFACE_INFO of m_axi_DATA_OUT_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_DATA_OUT WVALID";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "tiny_ecg_inference,Vivado 2026.1";
begin
end;
