// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_61_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        add_ln66,
        add_ln66_1,
        add_ln66_2,
        empty,
        sext_ln77,
        sext_ln71_1,
        buffer_c1_address0,
        buffer_c1_ce0,
        buffer_c1_we0,
        buffer_c1_d0,
        zext_ln60_1,
        buffer_c1_1_address0,
        buffer_c1_1_ce0,
        buffer_c1_1_we0,
        buffer_c1_1_d0,
        buffer_c1_2_address0,
        buffer_c1_2_ce0,
        buffer_c1_2_we0,
        buffer_c1_2_d0,
        buffer_c1_3_address0,
        buffer_c1_3_ce0,
        buffer_c1_3_we0,
        buffer_c1_3_d0,
        buffer_c1_4_address0,
        buffer_c1_4_ce0,
        buffer_c1_4_we0,
        buffer_c1_4_d0,
        buffer_c1_5_address0,
        buffer_c1_5_ce0,
        buffer_c1_5_we0,
        buffer_c1_5_d0,
        buffer_c1_6_address0,
        buffer_c1_6_ce0,
        buffer_c1_6_we0,
        buffer_c1_6_d0,
        buffer_c1_7_address0,
        buffer_c1_7_ce0,
        buffer_c1_7_we0,
        buffer_c1_7_d0,
        buffer_c1_8_address0,
        buffer_c1_8_ce0,
        buffer_c1_8_we0,
        buffer_c1_8_d0,
        buffer_c1_9_address0,
        buffer_c1_9_ce0,
        buffer_c1_9_we0,
        buffer_c1_9_d0,
        buffer_c1_10_address0,
        buffer_c1_10_ce0,
        buffer_c1_10_we0,
        buffer_c1_10_d0,
        buffer_c1_11_address0,
        buffer_c1_11_ce0,
        buffer_c1_11_we0,
        buffer_c1_11_d0,
        buffer_c1_12_address0,
        buffer_c1_12_ce0,
        buffer_c1_12_we0,
        buffer_c1_12_d0,
        buffer_c1_13_address0,
        buffer_c1_13_ce0,
        buffer_c1_13_we0,
        buffer_c1_13_d0,
        buffer_c1_14_address0,
        buffer_c1_14_ce0,
        buffer_c1_14_we0,
        buffer_c1_14_d0,
        buffer_c1_15_address0,
        buffer_c1_15_ce0,
        buffer_c1_15_we0,
        buffer_c1_15_d0,
        buffer_c1_16_address0,
        buffer_c1_16_ce0,
        buffer_c1_16_we0,
        buffer_c1_16_d0,
        buffer_c1_17_address0,
        buffer_c1_17_ce0,
        buffer_c1_17_we0,
        buffer_c1_17_d0,
        buffer_c1_18_address0,
        buffer_c1_18_ce0,
        buffer_c1_18_we0,
        buffer_c1_18_d0,
        buffer_c1_19_address0,
        buffer_c1_19_ce0,
        buffer_c1_19_we0,
        buffer_c1_19_d0,
        buffer_c1_20_address0,
        buffer_c1_20_ce0,
        buffer_c1_20_we0,
        buffer_c1_20_d0,
        buffer_c1_21_address0,
        buffer_c1_21_ce0,
        buffer_c1_21_we0,
        buffer_c1_21_d0,
        buffer_c1_22_address0,
        buffer_c1_22_ce0,
        buffer_c1_22_we0,
        buffer_c1_22_d0,
        buffer_c1_23_address0,
        buffer_c1_23_ce0,
        buffer_c1_23_we0,
        buffer_c1_23_d0,
        buffer_c1_24_address0,
        buffer_c1_24_ce0,
        buffer_c1_24_we0,
        buffer_c1_24_d0,
        buffer_c1_25_address0,
        buffer_c1_25_ce0,
        buffer_c1_25_we0,
        buffer_c1_25_d0,
        buffer_c1_26_address0,
        buffer_c1_26_ce0,
        buffer_c1_26_we0,
        buffer_c1_26_d0,
        buffer_c1_27_address0,
        buffer_c1_27_ce0,
        buffer_c1_27_we0,
        buffer_c1_27_d0,
        buffer_c1_28_address0,
        buffer_c1_28_ce0,
        buffer_c1_28_we0,
        buffer_c1_28_d0,
        buffer_c1_29_address0,
        buffer_c1_29_ce0,
        buffer_c1_29_we0,
        buffer_c1_29_d0,
        buffer_c1_30_address0,
        buffer_c1_30_ce0,
        buffer_c1_30_we0,
        buffer_c1_30_d0,
        buffer_c1_31_address0,
        buffer_c1_31_ce0,
        buffer_c1_31_we0,
        buffer_c1_31_d0,
        buffer_c1_32_address0,
        buffer_c1_32_ce0,
        buffer_c1_32_we0,
        buffer_c1_32_d0,
        buffer_c1_33_address0,
        buffer_c1_33_ce0,
        buffer_c1_33_we0,
        buffer_c1_33_d0,
        buffer_c1_34_address0,
        buffer_c1_34_ce0,
        buffer_c1_34_we0,
        buffer_c1_34_d0,
        buffer_c1_35_address0,
        buffer_c1_35_ce0,
        buffer_c1_35_we0,
        buffer_c1_35_d0,
        buffer_c1_36_address0,
        buffer_c1_36_ce0,
        buffer_c1_36_we0,
        buffer_c1_36_d0,
        buffer_c1_37_address0,
        buffer_c1_37_ce0,
        buffer_c1_37_we0,
        buffer_c1_37_d0,
        buffer_c1_38_address0,
        buffer_c1_38_ce0,
        buffer_c1_38_we0,
        buffer_c1_38_d0,
        buffer_c1_39_address0,
        buffer_c1_39_ce0,
        buffer_c1_39_we0,
        buffer_c1_39_d0,
        sext_ln71_3,
        sext_ln71_4,
        sext_ln71_5
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] add_ln66;
input  [7:0] add_ln66_1;
input  [6:0] add_ln66_2;
input  [2:0] empty;
input  [8:0] sext_ln77;
input  [8:0] sext_ln71_1;
output  [3:0] buffer_c1_address0;
output   buffer_c1_ce0;
output   buffer_c1_we0;
output  [6:0] buffer_c1_d0;
input  [3:0] zext_ln60_1;
output  [3:0] buffer_c1_1_address0;
output   buffer_c1_1_ce0;
output   buffer_c1_1_we0;
output  [6:0] buffer_c1_1_d0;
output  [3:0] buffer_c1_2_address0;
output   buffer_c1_2_ce0;
output   buffer_c1_2_we0;
output  [6:0] buffer_c1_2_d0;
output  [3:0] buffer_c1_3_address0;
output   buffer_c1_3_ce0;
output   buffer_c1_3_we0;
output  [6:0] buffer_c1_3_d0;
output  [3:0] buffer_c1_4_address0;
output   buffer_c1_4_ce0;
output   buffer_c1_4_we0;
output  [6:0] buffer_c1_4_d0;
output  [3:0] buffer_c1_5_address0;
output   buffer_c1_5_ce0;
output   buffer_c1_5_we0;
output  [6:0] buffer_c1_5_d0;
output  [3:0] buffer_c1_6_address0;
output   buffer_c1_6_ce0;
output   buffer_c1_6_we0;
output  [6:0] buffer_c1_6_d0;
output  [3:0] buffer_c1_7_address0;
output   buffer_c1_7_ce0;
output   buffer_c1_7_we0;
output  [6:0] buffer_c1_7_d0;
output  [3:0] buffer_c1_8_address0;
output   buffer_c1_8_ce0;
output   buffer_c1_8_we0;
output  [6:0] buffer_c1_8_d0;
output  [3:0] buffer_c1_9_address0;
output   buffer_c1_9_ce0;
output   buffer_c1_9_we0;
output  [6:0] buffer_c1_9_d0;
output  [3:0] buffer_c1_10_address0;
output   buffer_c1_10_ce0;
output   buffer_c1_10_we0;
output  [6:0] buffer_c1_10_d0;
output  [3:0] buffer_c1_11_address0;
output   buffer_c1_11_ce0;
output   buffer_c1_11_we0;
output  [6:0] buffer_c1_11_d0;
output  [3:0] buffer_c1_12_address0;
output   buffer_c1_12_ce0;
output   buffer_c1_12_we0;
output  [6:0] buffer_c1_12_d0;
output  [3:0] buffer_c1_13_address0;
output   buffer_c1_13_ce0;
output   buffer_c1_13_we0;
output  [6:0] buffer_c1_13_d0;
output  [3:0] buffer_c1_14_address0;
output   buffer_c1_14_ce0;
output   buffer_c1_14_we0;
output  [6:0] buffer_c1_14_d0;
output  [3:0] buffer_c1_15_address0;
output   buffer_c1_15_ce0;
output   buffer_c1_15_we0;
output  [6:0] buffer_c1_15_d0;
output  [3:0] buffer_c1_16_address0;
output   buffer_c1_16_ce0;
output   buffer_c1_16_we0;
output  [6:0] buffer_c1_16_d0;
output  [3:0] buffer_c1_17_address0;
output   buffer_c1_17_ce0;
output   buffer_c1_17_we0;
output  [6:0] buffer_c1_17_d0;
output  [3:0] buffer_c1_18_address0;
output   buffer_c1_18_ce0;
output   buffer_c1_18_we0;
output  [6:0] buffer_c1_18_d0;
output  [3:0] buffer_c1_19_address0;
output   buffer_c1_19_ce0;
output   buffer_c1_19_we0;
output  [6:0] buffer_c1_19_d0;
output  [3:0] buffer_c1_20_address0;
output   buffer_c1_20_ce0;
output   buffer_c1_20_we0;
output  [6:0] buffer_c1_20_d0;
output  [3:0] buffer_c1_21_address0;
output   buffer_c1_21_ce0;
output   buffer_c1_21_we0;
output  [6:0] buffer_c1_21_d0;
output  [3:0] buffer_c1_22_address0;
output   buffer_c1_22_ce0;
output   buffer_c1_22_we0;
output  [6:0] buffer_c1_22_d0;
output  [3:0] buffer_c1_23_address0;
output   buffer_c1_23_ce0;
output   buffer_c1_23_we0;
output  [6:0] buffer_c1_23_d0;
output  [3:0] buffer_c1_24_address0;
output   buffer_c1_24_ce0;
output   buffer_c1_24_we0;
output  [6:0] buffer_c1_24_d0;
output  [3:0] buffer_c1_25_address0;
output   buffer_c1_25_ce0;
output   buffer_c1_25_we0;
output  [6:0] buffer_c1_25_d0;
output  [3:0] buffer_c1_26_address0;
output   buffer_c1_26_ce0;
output   buffer_c1_26_we0;
output  [6:0] buffer_c1_26_d0;
output  [3:0] buffer_c1_27_address0;
output   buffer_c1_27_ce0;
output   buffer_c1_27_we0;
output  [6:0] buffer_c1_27_d0;
output  [3:0] buffer_c1_28_address0;
output   buffer_c1_28_ce0;
output   buffer_c1_28_we0;
output  [6:0] buffer_c1_28_d0;
output  [3:0] buffer_c1_29_address0;
output   buffer_c1_29_ce0;
output   buffer_c1_29_we0;
output  [6:0] buffer_c1_29_d0;
output  [3:0] buffer_c1_30_address0;
output   buffer_c1_30_ce0;
output   buffer_c1_30_we0;
output  [6:0] buffer_c1_30_d0;
output  [3:0] buffer_c1_31_address0;
output   buffer_c1_31_ce0;
output   buffer_c1_31_we0;
output  [6:0] buffer_c1_31_d0;
output  [3:0] buffer_c1_32_address0;
output   buffer_c1_32_ce0;
output   buffer_c1_32_we0;
output  [6:0] buffer_c1_32_d0;
output  [3:0] buffer_c1_33_address0;
output   buffer_c1_33_ce0;
output   buffer_c1_33_we0;
output  [6:0] buffer_c1_33_d0;
output  [3:0] buffer_c1_34_address0;
output   buffer_c1_34_ce0;
output   buffer_c1_34_we0;
output  [6:0] buffer_c1_34_d0;
output  [3:0] buffer_c1_35_address0;
output   buffer_c1_35_ce0;
output   buffer_c1_35_we0;
output  [6:0] buffer_c1_35_d0;
output  [3:0] buffer_c1_36_address0;
output   buffer_c1_36_ce0;
output   buffer_c1_36_we0;
output  [6:0] buffer_c1_36_d0;
output  [3:0] buffer_c1_37_address0;
output   buffer_c1_37_ce0;
output   buffer_c1_37_we0;
output  [6:0] buffer_c1_37_d0;
output  [3:0] buffer_c1_38_address0;
output   buffer_c1_38_ce0;
output   buffer_c1_38_we0;
output  [6:0] buffer_c1_38_d0;
output  [3:0] buffer_c1_39_address0;
output   buffer_c1_39_ce0;
output   buffer_c1_39_we0;
output  [6:0] buffer_c1_39_d0;
input  [7:0] sext_ln71_3;
input  [7:0] sext_ln71_4;
input  [7:0] sext_ln71_5;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln61_fu_981_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] conv1_weight_address0;
wire  signed [7:0] conv1_weight_q0;
wire   [5:0] conv1_weight_address1;
wire  signed [7:0] conv1_weight_q1;
wire   [5:0] conv1_weight_address2;
wire  signed [7:0] conv1_weight_q2;
wire   [5:0] conv1_weight_address3;
wire   [7:0] conv1_weight_q3;
wire   [5:0] conv1_weight_address4;
wire  signed [7:0] conv1_weight_q4;
wire   [2:0] conv1_multiplier_address0;
wire   [29:0] conv1_multiplier_q0;
wire   [2:0] conv1_shift_address0;
wire   [5:0] conv1_shift_q0;
wire   [2:0] conv1_bias_address0;
wire   [12:0] conv1_bias_q0;
wire   [2:0] tmp_reg_1336;
wire    ap_block_pp0_stage0_11001;
wire  signed [8:0] sext_ln69_fu_931_p1;
reg  signed [8:0] sext_ln69_reg_1340;
wire  signed [8:0] sext_ln69_1_fu_935_p1;
reg  signed [8:0] sext_ln69_1_reg_1345;
wire  signed [8:0] sext_ln69_2_fu_939_p1;
reg  signed [8:0] sext_ln69_2_reg_1350;
wire   [63:0] zext_ln69_fu_943_p1;
reg   [63:0] zext_ln69_reg_1355;
wire  signed [16:0] sext_ln69_3_fu_947_p1;
reg  signed [16:0] sext_ln69_3_reg_1399;
wire  signed [16:0] sext_ln69_4_fu_951_p1;
reg  signed [16:0] sext_ln69_4_reg_1404;
wire   [0:0] icmp_ln69_fu_955_p2;
reg   [0:0] icmp_ln69_reg_1409;
wire   [0:0] icmp_ln69_1_fu_961_p2;
reg   [0:0] icmp_ln69_1_reg_1413;
wire   [0:0] icmp_ln69_2_fu_967_p2;
reg   [0:0] icmp_ln69_2_reg_1417;
reg   [3:0] oc_1_reg_1421;
reg   [3:0] oc_1_reg_1421_pp0_iter1_reg;
reg   [3:0] oc_1_reg_1421_pp0_iter2_reg;
reg   [0:0] icmp_ln61_reg_1428;
reg   [0:0] icmp_ln61_reg_1428_pp0_iter1_reg;
reg   [0:0] icmp_ln61_reg_1428_pp0_iter2_reg;
wire   [2:0] trunc_ln61_fu_993_p1;
reg   [2:0] trunc_ln61_reg_1432;
reg   [2:0] trunc_ln61_reg_1432_pp0_iter1_reg;
reg   [2:0] trunc_ln61_reg_1432_pp0_iter2_reg;
reg   [2:0] trunc_ln61_reg_1432_pp0_iter3_reg;
reg   [2:0] trunc_ln61_reg_1432_pp0_iter4_reg;
reg   [2:0] trunc_ln61_reg_1432_pp0_iter5_reg;
reg   [2:0] trunc_ln61_reg_1432_pp0_iter6_reg;
reg   [2:0] trunc_ln61_reg_1432_pp0_iter7_reg;
reg   [2:0] trunc_ln61_reg_1432_pp0_iter8_reg;
wire   [5:0] add_ln69_fu_1030_p2;
reg   [5:0] add_ln69_reg_1436;
reg   [5:0] add_ln69_reg_1436_pp0_iter2_reg;
wire   [8:0] x_fu_1081_p2;
wire   [8:0] x_44_fu_1086_p2;
reg  signed [7:0] conv1_weight_load_3_reg_1494;
reg   [12:0] acc_reg_1509;
wire   [16:0] mul_ln74_fu_1119_p2;
reg   [16:0] mul_ln74_reg_1514;
wire  signed [16:0] mul_ln74_1_fu_1140_p2;
wire   [16:0] mul_ln74_2_fu_1145_p2;
reg   [16:0] mul_ln74_2_reg_1524;
wire   [16:0] mul_ln74_3_fu_1150_p2;
reg   [16:0] mul_ln74_3_reg_1529;
reg   [29:0] conv1_multiplier_load_reg_1534;
reg   [29:0] conv1_multiplier_load_reg_1534_pp0_iter5_reg;
reg   [5:0] conv1_shift_load_reg_1539;
reg   [5:0] conv1_shift_load_reg_1539_pp0_iter5_reg;
reg   [5:0] conv1_shift_load_reg_1539_pp0_iter6_reg;
reg   [5:0] conv1_shift_load_reg_1539_pp0_iter7_reg;
reg   [5:0] conv1_shift_load_reg_1539_pp0_iter8_reg;
wire   [18:0] acc_2_fu_1189_p2;
reg  signed [18:0] acc_2_reg_1545;
wire   [48:0] grp_fu_915_p2;
reg   [48:0] acc64_reg_1560;
wire   [5:0] add_ln10_fu_1203_p2;
reg   [5:0] add_ln10_reg_1565;
wire   [48:0] acc64_2_fu_1221_p2;
reg   [48:0] acc64_2_reg_1570;
wire   [0:0] icmp_ln20_fu_1264_p2;
reg   [0:0] icmp_ln20_reg_1575;
wire   [6:0] trunc_ln22_fu_1270_p1;
reg   [6:0] trunc_ln22_reg_1580;
reg  signed [8:0] ap_phi_mux_x_15_phi_fu_886_p4;
wire   [8:0] x_45_fu_1057_p2;
reg   [8:0] ap_phi_reg_pp0_iter2_x_15_reg_882;
wire   [8:0] ap_phi_reg_pp0_iter0_x_15_reg_882;
reg   [8:0] ap_phi_reg_pp0_iter1_x_15_reg_882;
wire   [8:0] ap_phi_reg_pp0_iter0_x_1_reg_893;
reg   [8:0] ap_phi_reg_pp0_iter1_x_1_reg_893;
reg   [8:0] ap_phi_reg_pp0_iter2_x_1_reg_893;
reg   [8:0] ap_phi_reg_pp0_iter3_x_1_reg_893;
reg  signed [8:0] ap_phi_reg_pp0_iter4_x_1_reg_893;
wire   [8:0] ap_phi_reg_pp0_iter0_x_3_reg_904;
reg   [8:0] ap_phi_reg_pp0_iter1_x_3_reg_904;
reg   [8:0] ap_phi_reg_pp0_iter2_x_3_reg_904;
reg   [8:0] ap_phi_reg_pp0_iter3_x_3_reg_904;
reg  signed [8:0] ap_phi_reg_pp0_iter4_x_3_reg_904;
wire   [63:0] zext_ln74_3_fu_1042_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln74_2_fu_1052_p1;
wire   [63:0] zext_ln61_fu_1071_p1;
wire   [63:0] zext_ln69_1_fu_1077_p1;
wire   [63:0] zext_ln74_fu_1096_p1;
wire   [63:0] zext_ln74_1_fu_1106_p1;
reg   [3:0] oc_fu_198;
wire   [3:0] add_ln61_fu_987_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_oc_1;
reg    conv1_weight_ce4_local;
reg    conv1_weight_ce3_local;
reg    conv1_weight_ce2_local;
reg    conv1_weight_ce1_local;
reg    conv1_weight_ce0_local;
reg    conv1_bias_ce0_local;
reg    conv1_multiplier_ce0_local;
reg    conv1_shift_ce0_local;
reg    buffer_c1_33_we0_local;
reg    ap_predicate_pred779_state11;
wire   [6:0] select_ln20_fu_1274_p3;
reg    buffer_c1_33_ce0_local;
reg    buffer_c1_32_we0_local;
reg    ap_predicate_pred794_state11;
reg    buffer_c1_32_ce0_local;
reg    buffer_c1_31_we0_local;
reg    ap_predicate_pred808_state11;
reg    buffer_c1_31_ce0_local;
reg    buffer_c1_30_we0_local;
reg    ap_predicate_pred822_state11;
reg    buffer_c1_30_ce0_local;
reg    buffer_c1_34_we0_local;
reg    ap_predicate_pred841_state11;
reg    buffer_c1_34_ce0_local;
reg    buffer_c1_28_we0_local;
reg    ap_predicate_pred855_state11;
reg    buffer_c1_28_ce0_local;
reg    buffer_c1_27_we0_local;
reg    ap_predicate_pred867_state11;
reg    buffer_c1_27_ce0_local;
reg    buffer_c1_26_we0_local;
reg    ap_predicate_pred879_state11;
reg    buffer_c1_26_ce0_local;
reg    buffer_c1_25_we0_local;
reg    ap_predicate_pred891_state11;
reg    buffer_c1_25_ce0_local;
reg    buffer_c1_29_we0_local;
reg    ap_predicate_pred906_state11;
reg    buffer_c1_29_ce0_local;
reg    buffer_c1_23_we0_local;
reg    ap_predicate_pred920_state11;
reg    buffer_c1_23_ce0_local;
reg    buffer_c1_22_we0_local;
reg    ap_predicate_pred932_state11;
reg    buffer_c1_22_ce0_local;
reg    buffer_c1_21_we0_local;
reg    ap_predicate_pred944_state11;
reg    buffer_c1_21_ce0_local;
reg    buffer_c1_20_we0_local;
reg    ap_predicate_pred956_state11;
reg    buffer_c1_20_ce0_local;
reg    buffer_c1_24_we0_local;
reg    ap_predicate_pred971_state11;
reg    buffer_c1_24_ce0_local;
reg    buffer_c1_18_we0_local;
reg    ap_predicate_pred984_state11;
reg    buffer_c1_18_ce0_local;
reg    buffer_c1_17_we0_local;
reg    ap_predicate_pred996_state11;
reg    buffer_c1_17_ce0_local;
reg    buffer_c1_16_we0_local;
reg    ap_predicate_pred1008_state11;
reg    buffer_c1_16_ce0_local;
reg    buffer_c1_15_we0_local;
reg    ap_predicate_pred1020_state11;
reg    buffer_c1_15_ce0_local;
reg    buffer_c1_19_we0_local;
reg    ap_predicate_pred1035_state11;
reg    buffer_c1_19_ce0_local;
reg    buffer_c1_13_we0_local;
reg    ap_predicate_pred1048_state11;
reg    buffer_c1_13_ce0_local;
reg    buffer_c1_12_we0_local;
reg    ap_predicate_pred1060_state11;
reg    buffer_c1_12_ce0_local;
reg    buffer_c1_11_we0_local;
reg    ap_predicate_pred1072_state11;
reg    buffer_c1_11_ce0_local;
reg    buffer_c1_10_we0_local;
reg    ap_predicate_pred1084_state11;
reg    buffer_c1_10_ce0_local;
reg    buffer_c1_14_we0_local;
reg    ap_predicate_pred1099_state11;
reg    buffer_c1_14_ce0_local;
reg    buffer_c1_8_we0_local;
reg    ap_predicate_pred1112_state11;
reg    buffer_c1_8_ce0_local;
reg    buffer_c1_7_we0_local;
reg    ap_predicate_pred1124_state11;
reg    buffer_c1_7_ce0_local;
reg    buffer_c1_6_we0_local;
reg    ap_predicate_pred1136_state11;
reg    buffer_c1_6_ce0_local;
reg    buffer_c1_5_we0_local;
reg    ap_predicate_pred1148_state11;
reg    buffer_c1_5_ce0_local;
reg    buffer_c1_9_we0_local;
reg    ap_predicate_pred1163_state11;
reg    buffer_c1_9_ce0_local;
reg    buffer_c1_3_we0_local;
reg    ap_predicate_pred1176_state11;
reg    buffer_c1_3_ce0_local;
reg    buffer_c1_2_we0_local;
reg    ap_predicate_pred1188_state11;
reg    buffer_c1_2_ce0_local;
reg    buffer_c1_1_we0_local;
reg    ap_predicate_pred1200_state11;
reg    buffer_c1_1_ce0_local;
reg    buffer_c1_we0_local;
reg    ap_predicate_pred1212_state11;
reg    buffer_c1_ce0_local;
reg    buffer_c1_4_we0_local;
reg    ap_predicate_pred1227_state11;
reg    buffer_c1_4_ce0_local;
reg    buffer_c1_38_we0_local;
reg    ap_predicate_pred1241_state11;
reg    buffer_c1_38_ce0_local;
reg    buffer_c1_37_we0_local;
reg    ap_predicate_pred1253_state11;
reg    buffer_c1_37_ce0_local;
reg    buffer_c1_36_we0_local;
reg    ap_predicate_pred1265_state11;
reg    buffer_c1_36_ce0_local;
reg    buffer_c1_35_we0_local;
reg    ap_predicate_pred1277_state11;
reg    buffer_c1_35_ce0_local;
reg    buffer_c1_39_we0_local;
reg    ap_predicate_pred1292_state11;
reg    buffer_c1_39_ce0_local;
wire   [29:0] grp_fu_915_p1;
wire   [5:0] p_shl_fu_1023_p3;
wire   [5:0] zext_ln61_1_fu_1020_p1;
wire   [5:0] add_ln74_3_fu_1036_p2;
wire   [5:0] add_ln74_2_fu_1047_p2;
wire   [5:0] add_ln74_fu_1091_p2;
wire   [5:0] add_ln74_1_fu_1101_p2;
wire  signed [8:0] mul_ln74_1_fu_1140_p0;
wire  signed [8:0] mul_ln74_2_fu_1145_p0;
wire   [16:0] add_ln74_4_fu_1162_p2;
wire  signed [16:0] sext_ln63_fu_1156_p1;
wire   [16:0] add_ln74_5_fu_1166_p2;
wire  signed [16:0] grp_fu_1320_p3;
wire  signed [17:0] sext_ln74_5_fu_1176_p1;
wire  signed [17:0] sext_ln74_2_fu_1159_p1;
wire   [17:0] add_ln74_7_fu_1179_p2;
wire  signed [18:0] sext_ln74_6_fu_1185_p1;
wire  signed [18:0] sext_ln74_4_fu_1172_p1;
wire   [36:0] zext_ln10_fu_1208_p1;
wire   [36:0] shl_ln10_fu_1211_p2;
wire   [48:0] zext_ln10_2_fu_1217_p1;
wire   [48:0] zext_ln13_fu_1226_p1;
wire   [48:0] res_fu_1229_p2;
wire   [0:0] tmp_8_fu_1238_p3;
wire   [12:0] trunc_ln13_fu_1234_p1;
wire   [12:0] res_2_fu_1246_p3;
wire   [5:0] tmp_9_fu_1254_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [48:0] grp_fu_915_p10;
reg    ap_condition_615;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 oc_fu_198 = 4'd0;
#0 ap_done_reg = 1'b0;
end

tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_61_2_conv1_weight_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 40 ),
    .AddressWidth( 6 ))
conv1_weight_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv1_weight_address0),
    .ce0(conv1_weight_ce0_local),
    .q0(conv1_weight_q0),
    .address1(conv1_weight_address1),
    .ce1(conv1_weight_ce1_local),
    .q1(conv1_weight_q1),
    .address2(conv1_weight_address2),
    .ce2(conv1_weight_ce2_local),
    .q2(conv1_weight_q2),
    .address3(conv1_weight_address3),
    .ce3(conv1_weight_ce3_local),
    .q3(conv1_weight_q3),
    .address4(conv1_weight_address4),
    .ce4(conv1_weight_ce4_local),
    .q4(conv1_weight_q4)
);

tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_61_2_conv1_multiplier_ROM_AUTO_1R #(
    .DataWidth( 30 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
conv1_multiplier_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv1_multiplier_address0),
    .ce0(conv1_multiplier_ce0_local),
    .q0(conv1_multiplier_q0)
);

tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_61_2_conv1_shift_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
conv1_shift_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv1_shift_address0),
    .ce0(conv1_shift_ce0_local),
    .q0(conv1_shift_q0)
);

tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_61_2_conv1_bias_ROM_AUTO_1R #(
    .DataWidth( 13 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
conv1_bias_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv1_bias_address0),
    .ce0(conv1_bias_ce0_local),
    .q0(conv1_bias_q0)
);

tiny_ecg_inference_mul_19s_30ns_49_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 19 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 49 ))
mul_19s_30ns_49_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_2_reg_1545),
    .din1(grp_fu_915_p1),
    .ce(1'b1),
    .dout(grp_fu_915_p2)
);

tiny_ecg_inference_mul_9s_8s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 17 ))
mul_9s_8s_17_1_1_U2(
    .din0(ap_phi_reg_pp0_iter4_x_1_reg_893),
    .din1(conv1_weight_q2),
    .dout(mul_ln74_fu_1119_p2)
);

tiny_ecg_inference_mul_9s_8s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 17 ))
mul_9s_8s_17_1_1_U3(
    .din0(mul_ln74_1_fu_1140_p0),
    .din1(conv1_weight_load_3_reg_1494),
    .dout(mul_ln74_1_fu_1140_p2)
);

tiny_ecg_inference_mul_9s_8s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 17 ))
mul_9s_8s_17_1_1_U4(
    .din0(mul_ln74_2_fu_1145_p0),
    .din1(conv1_weight_q0),
    .dout(mul_ln74_2_fu_1145_p2)
);

tiny_ecg_inference_mul_9s_8s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 17 ))
mul_9s_8s_17_1_1_U5(
    .din0(ap_phi_reg_pp0_iter4_x_3_reg_904),
    .din1(conv1_weight_q1),
    .dout(mul_ln74_3_fu_1150_p2)
);

tiny_ecg_inference_mac_muladd_9s_8s_17s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_9s_8s_17s_17_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_phi_mux_x_15_phi_fu_886_p4),
    .din1(conv1_weight_q4),
    .din2(mul_ln74_1_fu_1140_p2),
    .ce(1'b1),
    .dout(grp_fu_1320_p3)
);

tiny_ecg_inference_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_615)) begin
        if (((icmp_ln61_fu_981_p2 == 1'd0) & (icmp_ln69_2_fu_967_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_x_15_reg_882 <= 9'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_x_15_reg_882 <= ap_phi_reg_pp0_iter0_x_15_reg_882;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_615)) begin
        if (((icmp_ln61_fu_981_p2 == 1'd0) & (icmp_ln69_fu_955_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_x_1_reg_893 <= 9'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_x_1_reg_893 <= ap_phi_reg_pp0_iter0_x_1_reg_893;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_615)) begin
        if (((icmp_ln61_fu_981_p2 == 1'd0) & (icmp_ln69_1_fu_961_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_x_3_reg_904 <= 9'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_x_3_reg_904 <= ap_phi_reg_pp0_iter0_x_3_reg_904;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln61_reg_1428_pp0_iter2_reg == 1'd0) & (icmp_ln69_reg_1409 == 1'd1))) begin
            ap_phi_reg_pp0_iter4_x_1_reg_893 <= x_fu_1081_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_x_1_reg_893 <= ap_phi_reg_pp0_iter3_x_1_reg_893;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln61_reg_1428_pp0_iter2_reg == 1'd0) & (icmp_ln69_1_reg_1413 == 1'd1))) begin
            ap_phi_reg_pp0_iter4_x_3_reg_904 <= x_44_fu_1086_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_x_3_reg_904 <= ap_phi_reg_pp0_iter3_x_3_reg_904;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln61_fu_981_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            oc_fu_198 <= add_ln61_fu_987_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            oc_fu_198 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        acc64_2_reg_1570 <= acc64_2_fu_1221_p2;
        acc64_reg_1560 <= grp_fu_915_p2;
        acc_2_reg_1545 <= acc_2_fu_1189_p2;
        acc_reg_1509 <= conv1_bias_q0;
        add_ln10_reg_1565 <= add_ln10_fu_1203_p2;
        add_ln69_reg_1436_pp0_iter2_reg <= add_ln69_reg_1436;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        ap_predicate_pred1008_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd3) & (tmp_reg_1336 == 3'd1));
        ap_predicate_pred1020_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd3) & (tmp_reg_1336 == 3'd0));
        ap_predicate_pred1035_state11 <= (~(tmp_reg_1336 == 3'd0) & ~(tmp_reg_1336 == 3'd1) & ~(tmp_reg_1336 == 3'd2) & ~(tmp_reg_1336 == 3'd3) & (trunc_ln61_reg_1432_pp0_iter8_reg == 3'd3));
        ap_predicate_pred1048_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd2) & (tmp_reg_1336 == 3'd3));
        ap_predicate_pred1060_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd2) & (tmp_reg_1336 == 3'd2));
        ap_predicate_pred1072_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd2) & (tmp_reg_1336 == 3'd1));
        ap_predicate_pred1084_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd2) & (tmp_reg_1336 == 3'd0));
        ap_predicate_pred1099_state11 <= (~(tmp_reg_1336 == 3'd0) & ~(tmp_reg_1336 == 3'd1) & ~(tmp_reg_1336 == 3'd2) & ~(tmp_reg_1336 == 3'd3) & (trunc_ln61_reg_1432_pp0_iter8_reg == 3'd2));
        ap_predicate_pred1112_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd1) & (tmp_reg_1336 == 3'd3));
        ap_predicate_pred1124_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd1) & (tmp_reg_1336 == 3'd2));
        ap_predicate_pred1136_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd1) & (tmp_reg_1336 == 3'd1));
        ap_predicate_pred1148_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd1) & (tmp_reg_1336 == 3'd0));
        ap_predicate_pred1163_state11 <= (~(tmp_reg_1336 == 3'd0) & ~(tmp_reg_1336 == 3'd1) & ~(tmp_reg_1336 == 3'd2) & ~(tmp_reg_1336 == 3'd3) & (trunc_ln61_reg_1432_pp0_iter8_reg == 3'd1));
        ap_predicate_pred1176_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd0) & (tmp_reg_1336 == 3'd3));
        ap_predicate_pred1188_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd0) & (tmp_reg_1336 == 3'd2));
        ap_predicate_pred1200_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd0) & (tmp_reg_1336 == 3'd1));
        ap_predicate_pred1212_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd0) & (tmp_reg_1336 == 3'd0));
        ap_predicate_pred1227_state11 <= (~(tmp_reg_1336 == 3'd0) & ~(tmp_reg_1336 == 3'd1) & ~(tmp_reg_1336 == 3'd2) & ~(tmp_reg_1336 == 3'd3) & (trunc_ln61_reg_1432_pp0_iter8_reg == 3'd0));
        ap_predicate_pred1241_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd7) & (tmp_reg_1336 == 3'd3));
        ap_predicate_pred1253_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd7) & (tmp_reg_1336 == 3'd2));
        ap_predicate_pred1265_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd7) & (tmp_reg_1336 == 3'd1));
        ap_predicate_pred1277_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd7) & (tmp_reg_1336 == 3'd0));
        ap_predicate_pred1292_state11 <= (~(tmp_reg_1336 == 3'd0) & ~(tmp_reg_1336 == 3'd1) & ~(tmp_reg_1336 == 3'd2) & ~(tmp_reg_1336 == 3'd3) & (trunc_ln61_reg_1432_pp0_iter8_reg == 3'd7));
        ap_predicate_pred779_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd6) & (tmp_reg_1336 == 3'd3));
        ap_predicate_pred794_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd6) & (tmp_reg_1336 == 3'd2));
        ap_predicate_pred808_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd6) & (tmp_reg_1336 == 3'd1));
        ap_predicate_pred822_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd6) & (tmp_reg_1336 == 3'd0));
        ap_predicate_pred841_state11 <= (~(tmp_reg_1336 == 3'd0) & ~(tmp_reg_1336 == 3'd1) & ~(tmp_reg_1336 == 3'd2) & ~(tmp_reg_1336 == 3'd3) & (trunc_ln61_reg_1432_pp0_iter8_reg == 3'd6));
        ap_predicate_pred855_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd5) & (tmp_reg_1336 == 3'd3));
        ap_predicate_pred867_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd5) & (tmp_reg_1336 == 3'd2));
        ap_predicate_pred879_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd5) & (tmp_reg_1336 == 3'd1));
        ap_predicate_pred891_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd5) & (tmp_reg_1336 == 3'd0));
        ap_predicate_pred906_state11 <= (~(tmp_reg_1336 == 3'd0) & ~(tmp_reg_1336 == 3'd1) & ~(tmp_reg_1336 == 3'd2) & ~(tmp_reg_1336 == 3'd3) & (trunc_ln61_reg_1432_pp0_iter8_reg == 3'd5));
        ap_predicate_pred920_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd4) & (tmp_reg_1336 == 3'd3));
        ap_predicate_pred932_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd4) & (tmp_reg_1336 == 3'd2));
        ap_predicate_pred944_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd4) & (tmp_reg_1336 == 3'd1));
        ap_predicate_pred956_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd4) & (tmp_reg_1336 == 3'd0));
        ap_predicate_pred971_state11 <= (~(tmp_reg_1336 == 3'd0) & ~(tmp_reg_1336 == 3'd1) & ~(tmp_reg_1336 == 3'd2) & ~(tmp_reg_1336 == 3'd3) & (trunc_ln61_reg_1432_pp0_iter8_reg == 3'd4));
        ap_predicate_pred984_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd3) & (tmp_reg_1336 == 3'd3));
        ap_predicate_pred996_state11 <= ((trunc_ln61_reg_1432_pp0_iter8_reg == 3'd3) & (tmp_reg_1336 == 3'd2));
        conv1_multiplier_load_reg_1534 <= conv1_multiplier_q0;
        conv1_multiplier_load_reg_1534_pp0_iter5_reg <= conv1_multiplier_load_reg_1534;
        conv1_shift_load_reg_1539 <= conv1_shift_q0;
        conv1_shift_load_reg_1539_pp0_iter5_reg <= conv1_shift_load_reg_1539;
        conv1_shift_load_reg_1539_pp0_iter6_reg <= conv1_shift_load_reg_1539_pp0_iter5_reg;
        conv1_shift_load_reg_1539_pp0_iter7_reg <= conv1_shift_load_reg_1539_pp0_iter6_reg;
        conv1_shift_load_reg_1539_pp0_iter8_reg <= conv1_shift_load_reg_1539_pp0_iter7_reg;
        icmp_ln20_reg_1575 <= icmp_ln20_fu_1264_p2;
        icmp_ln61_reg_1428_pp0_iter2_reg <= icmp_ln61_reg_1428_pp0_iter1_reg;
        mul_ln74_2_reg_1524 <= mul_ln74_2_fu_1145_p2;
        mul_ln74_3_reg_1529 <= mul_ln74_3_fu_1150_p2;
        mul_ln74_reg_1514 <= mul_ln74_fu_1119_p2;
        oc_1_reg_1421_pp0_iter2_reg <= oc_1_reg_1421_pp0_iter1_reg;
        trunc_ln22_reg_1580 <= trunc_ln22_fu_1270_p1;
        trunc_ln61_reg_1432_pp0_iter2_reg <= trunc_ln61_reg_1432_pp0_iter1_reg;
        trunc_ln61_reg_1432_pp0_iter3_reg <= trunc_ln61_reg_1432_pp0_iter2_reg;
        trunc_ln61_reg_1432_pp0_iter4_reg <= trunc_ln61_reg_1432_pp0_iter3_reg;
        trunc_ln61_reg_1432_pp0_iter5_reg <= trunc_ln61_reg_1432_pp0_iter4_reg;
        trunc_ln61_reg_1432_pp0_iter6_reg <= trunc_ln61_reg_1432_pp0_iter5_reg;
        trunc_ln61_reg_1432_pp0_iter7_reg <= trunc_ln61_reg_1432_pp0_iter6_reg;
        trunc_ln61_reg_1432_pp0_iter8_reg <= trunc_ln61_reg_1432_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln69_reg_1436 <= add_ln69_fu_1030_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln61_reg_1428 <= icmp_ln61_fu_981_p2;
        icmp_ln61_reg_1428_pp0_iter1_reg <= icmp_ln61_reg_1428;
        icmp_ln69_1_reg_1413 <= icmp_ln69_1_fu_961_p2;
        icmp_ln69_2_reg_1417 <= icmp_ln69_2_fu_967_p2;
        icmp_ln69_reg_1409 <= icmp_ln69_fu_955_p2;
        oc_1_reg_1421 <= ap_sig_allocacmp_oc_1;
        oc_1_reg_1421_pp0_iter1_reg <= oc_1_reg_1421;
        sext_ln69_1_reg_1345 <= sext_ln69_1_fu_935_p1;
        sext_ln69_2_reg_1350 <= sext_ln69_2_fu_939_p1;
        sext_ln69_3_reg_1399 <= sext_ln69_3_fu_947_p1;
        sext_ln69_4_reg_1404 <= sext_ln69_4_fu_951_p1;
        sext_ln69_reg_1340 <= sext_ln69_fu_931_p1;
        trunc_ln61_reg_1432 <= trunc_ln61_fu_993_p1;
        trunc_ln61_reg_1432_pp0_iter1_reg <= trunc_ln61_reg_1432;
        zext_ln69_reg_1355[3 : 0] <= zext_ln69_fu_943_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_x_15_reg_882 <= ap_phi_reg_pp0_iter1_x_15_reg_882;
        ap_phi_reg_pp0_iter2_x_1_reg_893 <= ap_phi_reg_pp0_iter1_x_1_reg_893;
        ap_phi_reg_pp0_iter2_x_3_reg_904 <= ap_phi_reg_pp0_iter1_x_3_reg_904;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_x_1_reg_893 <= ap_phi_reg_pp0_iter2_x_1_reg_893;
        ap_phi_reg_pp0_iter3_x_3_reg_904 <= ap_phi_reg_pp0_iter2_x_3_reg_904;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        conv1_weight_load_3_reg_1494 <= conv1_weight_q3;
    end
end

always @ (*) begin
    if (((icmp_ln61_fu_981_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln61_reg_1428_pp0_iter1_reg == 1'd0) & (icmp_ln69_2_reg_1417 == 1'd1))) begin
        ap_phi_mux_x_15_phi_fu_886_p4 = x_45_fu_1057_p2;
    end else begin
        ap_phi_mux_x_15_phi_fu_886_p4 = ap_phi_reg_pp0_iter2_x_15_reg_882;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_oc_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_oc_1 = oc_fu_198;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_10_ce0_local = 1'b1;
    end else begin
        buffer_c1_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1084_state11 == 1'b1))) begin
        buffer_c1_10_we0_local = 1'b1;
    end else begin
        buffer_c1_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_11_ce0_local = 1'b1;
    end else begin
        buffer_c1_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1072_state11 == 1'b1))) begin
        buffer_c1_11_we0_local = 1'b1;
    end else begin
        buffer_c1_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_12_ce0_local = 1'b1;
    end else begin
        buffer_c1_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1060_state11 == 1'b1))) begin
        buffer_c1_12_we0_local = 1'b1;
    end else begin
        buffer_c1_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_13_ce0_local = 1'b1;
    end else begin
        buffer_c1_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1048_state11 == 1'b1))) begin
        buffer_c1_13_we0_local = 1'b1;
    end else begin
        buffer_c1_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_14_ce0_local = 1'b1;
    end else begin
        buffer_c1_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1099_state11 == 1'b1))) begin
        buffer_c1_14_we0_local = 1'b1;
    end else begin
        buffer_c1_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_15_ce0_local = 1'b1;
    end else begin
        buffer_c1_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1020_state11 == 1'b1))) begin
        buffer_c1_15_we0_local = 1'b1;
    end else begin
        buffer_c1_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_16_ce0_local = 1'b1;
    end else begin
        buffer_c1_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1008_state11 == 1'b1))) begin
        buffer_c1_16_we0_local = 1'b1;
    end else begin
        buffer_c1_16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_17_ce0_local = 1'b1;
    end else begin
        buffer_c1_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred996_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_17_we0_local = 1'b1;
    end else begin
        buffer_c1_17_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_18_ce0_local = 1'b1;
    end else begin
        buffer_c1_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred984_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_18_we0_local = 1'b1;
    end else begin
        buffer_c1_18_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_19_ce0_local = 1'b1;
    end else begin
        buffer_c1_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1035_state11 == 1'b1))) begin
        buffer_c1_19_we0_local = 1'b1;
    end else begin
        buffer_c1_19_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_1_ce0_local = 1'b1;
    end else begin
        buffer_c1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1200_state11 == 1'b1))) begin
        buffer_c1_1_we0_local = 1'b1;
    end else begin
        buffer_c1_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_20_ce0_local = 1'b1;
    end else begin
        buffer_c1_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred956_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_20_we0_local = 1'b1;
    end else begin
        buffer_c1_20_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_21_ce0_local = 1'b1;
    end else begin
        buffer_c1_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred944_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_21_we0_local = 1'b1;
    end else begin
        buffer_c1_21_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_22_ce0_local = 1'b1;
    end else begin
        buffer_c1_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred932_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_22_we0_local = 1'b1;
    end else begin
        buffer_c1_22_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_23_ce0_local = 1'b1;
    end else begin
        buffer_c1_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred920_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_23_we0_local = 1'b1;
    end else begin
        buffer_c1_23_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_24_ce0_local = 1'b1;
    end else begin
        buffer_c1_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred971_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_24_we0_local = 1'b1;
    end else begin
        buffer_c1_24_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_25_ce0_local = 1'b1;
    end else begin
        buffer_c1_25_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred891_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_25_we0_local = 1'b1;
    end else begin
        buffer_c1_25_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_26_ce0_local = 1'b1;
    end else begin
        buffer_c1_26_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred879_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_26_we0_local = 1'b1;
    end else begin
        buffer_c1_26_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_27_ce0_local = 1'b1;
    end else begin
        buffer_c1_27_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred867_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_27_we0_local = 1'b1;
    end else begin
        buffer_c1_27_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_28_ce0_local = 1'b1;
    end else begin
        buffer_c1_28_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred855_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_28_we0_local = 1'b1;
    end else begin
        buffer_c1_28_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_29_ce0_local = 1'b1;
    end else begin
        buffer_c1_29_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred906_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_29_we0_local = 1'b1;
    end else begin
        buffer_c1_29_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_2_ce0_local = 1'b1;
    end else begin
        buffer_c1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1188_state11 == 1'b1))) begin
        buffer_c1_2_we0_local = 1'b1;
    end else begin
        buffer_c1_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_30_ce0_local = 1'b1;
    end else begin
        buffer_c1_30_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred822_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_30_we0_local = 1'b1;
    end else begin
        buffer_c1_30_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_31_ce0_local = 1'b1;
    end else begin
        buffer_c1_31_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred808_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_31_we0_local = 1'b1;
    end else begin
        buffer_c1_31_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_32_ce0_local = 1'b1;
    end else begin
        buffer_c1_32_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred794_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_32_we0_local = 1'b1;
    end else begin
        buffer_c1_32_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_33_ce0_local = 1'b1;
    end else begin
        buffer_c1_33_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred779_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_33_we0_local = 1'b1;
    end else begin
        buffer_c1_33_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_34_ce0_local = 1'b1;
    end else begin
        buffer_c1_34_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred841_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_34_we0_local = 1'b1;
    end else begin
        buffer_c1_34_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_35_ce0_local = 1'b1;
    end else begin
        buffer_c1_35_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1277_state11 == 1'b1))) begin
        buffer_c1_35_we0_local = 1'b1;
    end else begin
        buffer_c1_35_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_36_ce0_local = 1'b1;
    end else begin
        buffer_c1_36_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1265_state11 == 1'b1))) begin
        buffer_c1_36_we0_local = 1'b1;
    end else begin
        buffer_c1_36_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_37_ce0_local = 1'b1;
    end else begin
        buffer_c1_37_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1253_state11 == 1'b1))) begin
        buffer_c1_37_we0_local = 1'b1;
    end else begin
        buffer_c1_37_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_38_ce0_local = 1'b1;
    end else begin
        buffer_c1_38_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1241_state11 == 1'b1))) begin
        buffer_c1_38_we0_local = 1'b1;
    end else begin
        buffer_c1_38_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_39_ce0_local = 1'b1;
    end else begin
        buffer_c1_39_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1292_state11 == 1'b1))) begin
        buffer_c1_39_we0_local = 1'b1;
    end else begin
        buffer_c1_39_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_3_ce0_local = 1'b1;
    end else begin
        buffer_c1_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1176_state11 == 1'b1))) begin
        buffer_c1_3_we0_local = 1'b1;
    end else begin
        buffer_c1_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_4_ce0_local = 1'b1;
    end else begin
        buffer_c1_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1227_state11 == 1'b1))) begin
        buffer_c1_4_we0_local = 1'b1;
    end else begin
        buffer_c1_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_5_ce0_local = 1'b1;
    end else begin
        buffer_c1_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1148_state11 == 1'b1))) begin
        buffer_c1_5_we0_local = 1'b1;
    end else begin
        buffer_c1_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_6_ce0_local = 1'b1;
    end else begin
        buffer_c1_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1136_state11 == 1'b1))) begin
        buffer_c1_6_we0_local = 1'b1;
    end else begin
        buffer_c1_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_7_ce0_local = 1'b1;
    end else begin
        buffer_c1_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1124_state11 == 1'b1))) begin
        buffer_c1_7_we0_local = 1'b1;
    end else begin
        buffer_c1_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_8_ce0_local = 1'b1;
    end else begin
        buffer_c1_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1112_state11 == 1'b1))) begin
        buffer_c1_8_we0_local = 1'b1;
    end else begin
        buffer_c1_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_9_ce0_local = 1'b1;
    end else begin
        buffer_c1_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1163_state11 == 1'b1))) begin
        buffer_c1_9_we0_local = 1'b1;
    end else begin
        buffer_c1_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        buffer_c1_ce0_local = 1'b1;
    end else begin
        buffer_c1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_pred1212_state11 == 1'b1))) begin
        buffer_c1_we0_local = 1'b1;
    end else begin
        buffer_c1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        conv1_bias_ce0_local = 1'b1;
    end else begin
        conv1_bias_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        conv1_multiplier_ce0_local = 1'b1;
    end else begin
        conv1_multiplier_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        conv1_shift_ce0_local = 1'b1;
    end else begin
        conv1_shift_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        conv1_weight_ce0_local = 1'b1;
    end else begin
        conv1_weight_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        conv1_weight_ce1_local = 1'b1;
    end else begin
        conv1_weight_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        conv1_weight_ce2_local = 1'b1;
    end else begin
        conv1_weight_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        conv1_weight_ce3_local = 1'b1;
    end else begin
        conv1_weight_ce3_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_weight_ce4_local = 1'b1;
    end else begin
        conv1_weight_ce4_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc64_2_fu_1221_p2 = (zext_ln10_2_fu_1217_p1 + acc64_reg_1560);

assign acc_2_fu_1189_p2 = ($signed(sext_ln74_6_fu_1185_p1) + $signed(sext_ln74_4_fu_1172_p1));

assign add_ln10_fu_1203_p2 = ($signed(conv1_shift_load_reg_1539_pp0_iter6_reg) + $signed(6'd63));

assign add_ln61_fu_987_p2 = (ap_sig_allocacmp_oc_1 + 4'd1);

assign add_ln69_fu_1030_p2 = (p_shl_fu_1023_p3 + zext_ln61_1_fu_1020_p1);

assign add_ln74_1_fu_1101_p2 = (add_ln69_reg_1436_pp0_iter2_reg + 6'd2);

assign add_ln74_2_fu_1047_p2 = (add_ln69_reg_1436 + 6'd3);

assign add_ln74_3_fu_1036_p2 = (add_ln69_fu_1030_p2 + 6'd4);

assign add_ln74_4_fu_1162_p2 = (mul_ln74_reg_1514 + mul_ln74_3_reg_1529);

assign add_ln74_5_fu_1166_p2 = ($signed(add_ln74_4_fu_1162_p2) + $signed(sext_ln63_fu_1156_p1));

assign add_ln74_7_fu_1179_p2 = ($signed(sext_ln74_5_fu_1176_p1) + $signed(sext_ln74_2_fu_1159_p1));

assign add_ln74_fu_1091_p2 = (add_ln69_reg_1436_pp0_iter2_reg + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_615 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_x_15_reg_882 = 'bx;

assign ap_phi_reg_pp0_iter0_x_1_reg_893 = 'bx;

assign ap_phi_reg_pp0_iter0_x_3_reg_904 = 'bx;

assign ap_ready = ap_ready_sig;

assign buffer_c1_10_address0 = zext_ln69_reg_1355;

assign buffer_c1_10_ce0 = buffer_c1_10_ce0_local;

assign buffer_c1_10_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_10_we0 = buffer_c1_10_we0_local;

assign buffer_c1_11_address0 = zext_ln69_reg_1355;

assign buffer_c1_11_ce0 = buffer_c1_11_ce0_local;

assign buffer_c1_11_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_11_we0 = buffer_c1_11_we0_local;

assign buffer_c1_12_address0 = zext_ln69_reg_1355;

assign buffer_c1_12_ce0 = buffer_c1_12_ce0_local;

assign buffer_c1_12_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_12_we0 = buffer_c1_12_we0_local;

assign buffer_c1_13_address0 = zext_ln69_reg_1355;

assign buffer_c1_13_ce0 = buffer_c1_13_ce0_local;

assign buffer_c1_13_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_13_we0 = buffer_c1_13_we0_local;

assign buffer_c1_14_address0 = zext_ln69_reg_1355;

assign buffer_c1_14_ce0 = buffer_c1_14_ce0_local;

assign buffer_c1_14_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_14_we0 = buffer_c1_14_we0_local;

assign buffer_c1_15_address0 = zext_ln69_reg_1355;

assign buffer_c1_15_ce0 = buffer_c1_15_ce0_local;

assign buffer_c1_15_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_15_we0 = buffer_c1_15_we0_local;

assign buffer_c1_16_address0 = zext_ln69_reg_1355;

assign buffer_c1_16_ce0 = buffer_c1_16_ce0_local;

assign buffer_c1_16_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_16_we0 = buffer_c1_16_we0_local;

assign buffer_c1_17_address0 = zext_ln69_reg_1355;

assign buffer_c1_17_ce0 = buffer_c1_17_ce0_local;

assign buffer_c1_17_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_17_we0 = buffer_c1_17_we0_local;

assign buffer_c1_18_address0 = zext_ln69_reg_1355;

assign buffer_c1_18_ce0 = buffer_c1_18_ce0_local;

assign buffer_c1_18_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_18_we0 = buffer_c1_18_we0_local;

assign buffer_c1_19_address0 = zext_ln69_reg_1355;

assign buffer_c1_19_ce0 = buffer_c1_19_ce0_local;

assign buffer_c1_19_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_19_we0 = buffer_c1_19_we0_local;

assign buffer_c1_1_address0 = zext_ln69_reg_1355;

assign buffer_c1_1_ce0 = buffer_c1_1_ce0_local;

assign buffer_c1_1_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_1_we0 = buffer_c1_1_we0_local;

assign buffer_c1_20_address0 = zext_ln69_reg_1355;

assign buffer_c1_20_ce0 = buffer_c1_20_ce0_local;

assign buffer_c1_20_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_20_we0 = buffer_c1_20_we0_local;

assign buffer_c1_21_address0 = zext_ln69_reg_1355;

assign buffer_c1_21_ce0 = buffer_c1_21_ce0_local;

assign buffer_c1_21_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_21_we0 = buffer_c1_21_we0_local;

assign buffer_c1_22_address0 = zext_ln69_reg_1355;

assign buffer_c1_22_ce0 = buffer_c1_22_ce0_local;

assign buffer_c1_22_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_22_we0 = buffer_c1_22_we0_local;

assign buffer_c1_23_address0 = zext_ln69_reg_1355;

assign buffer_c1_23_ce0 = buffer_c1_23_ce0_local;

assign buffer_c1_23_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_23_we0 = buffer_c1_23_we0_local;

assign buffer_c1_24_address0 = zext_ln69_reg_1355;

assign buffer_c1_24_ce0 = buffer_c1_24_ce0_local;

assign buffer_c1_24_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_24_we0 = buffer_c1_24_we0_local;

assign buffer_c1_25_address0 = zext_ln69_reg_1355;

assign buffer_c1_25_ce0 = buffer_c1_25_ce0_local;

assign buffer_c1_25_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_25_we0 = buffer_c1_25_we0_local;

assign buffer_c1_26_address0 = zext_ln69_reg_1355;

assign buffer_c1_26_ce0 = buffer_c1_26_ce0_local;

assign buffer_c1_26_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_26_we0 = buffer_c1_26_we0_local;

assign buffer_c1_27_address0 = zext_ln69_reg_1355;

assign buffer_c1_27_ce0 = buffer_c1_27_ce0_local;

assign buffer_c1_27_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_27_we0 = buffer_c1_27_we0_local;

assign buffer_c1_28_address0 = zext_ln69_reg_1355;

assign buffer_c1_28_ce0 = buffer_c1_28_ce0_local;

assign buffer_c1_28_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_28_we0 = buffer_c1_28_we0_local;

assign buffer_c1_29_address0 = zext_ln69_reg_1355;

assign buffer_c1_29_ce0 = buffer_c1_29_ce0_local;

assign buffer_c1_29_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_29_we0 = buffer_c1_29_we0_local;

assign buffer_c1_2_address0 = zext_ln69_reg_1355;

assign buffer_c1_2_ce0 = buffer_c1_2_ce0_local;

assign buffer_c1_2_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_2_we0 = buffer_c1_2_we0_local;

assign buffer_c1_30_address0 = zext_ln69_reg_1355;

assign buffer_c1_30_ce0 = buffer_c1_30_ce0_local;

assign buffer_c1_30_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_30_we0 = buffer_c1_30_we0_local;

assign buffer_c1_31_address0 = zext_ln69_reg_1355;

assign buffer_c1_31_ce0 = buffer_c1_31_ce0_local;

assign buffer_c1_31_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_31_we0 = buffer_c1_31_we0_local;

assign buffer_c1_32_address0 = zext_ln69_reg_1355;

assign buffer_c1_32_ce0 = buffer_c1_32_ce0_local;

assign buffer_c1_32_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_32_we0 = buffer_c1_32_we0_local;

assign buffer_c1_33_address0 = zext_ln69_reg_1355;

assign buffer_c1_33_ce0 = buffer_c1_33_ce0_local;

assign buffer_c1_33_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_33_we0 = buffer_c1_33_we0_local;

assign buffer_c1_34_address0 = zext_ln69_reg_1355;

assign buffer_c1_34_ce0 = buffer_c1_34_ce0_local;

assign buffer_c1_34_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_34_we0 = buffer_c1_34_we0_local;

assign buffer_c1_35_address0 = zext_ln69_reg_1355;

assign buffer_c1_35_ce0 = buffer_c1_35_ce0_local;

assign buffer_c1_35_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_35_we0 = buffer_c1_35_we0_local;

assign buffer_c1_36_address0 = zext_ln69_reg_1355;

assign buffer_c1_36_ce0 = buffer_c1_36_ce0_local;

assign buffer_c1_36_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_36_we0 = buffer_c1_36_we0_local;

assign buffer_c1_37_address0 = zext_ln69_reg_1355;

assign buffer_c1_37_ce0 = buffer_c1_37_ce0_local;

assign buffer_c1_37_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_37_we0 = buffer_c1_37_we0_local;

assign buffer_c1_38_address0 = zext_ln69_reg_1355;

assign buffer_c1_38_ce0 = buffer_c1_38_ce0_local;

assign buffer_c1_38_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_38_we0 = buffer_c1_38_we0_local;

assign buffer_c1_39_address0 = zext_ln69_reg_1355;

assign buffer_c1_39_ce0 = buffer_c1_39_ce0_local;

assign buffer_c1_39_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_39_we0 = buffer_c1_39_we0_local;

assign buffer_c1_3_address0 = zext_ln69_reg_1355;

assign buffer_c1_3_ce0 = buffer_c1_3_ce0_local;

assign buffer_c1_3_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_3_we0 = buffer_c1_3_we0_local;

assign buffer_c1_4_address0 = zext_ln69_reg_1355;

assign buffer_c1_4_ce0 = buffer_c1_4_ce0_local;

assign buffer_c1_4_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_4_we0 = buffer_c1_4_we0_local;

assign buffer_c1_5_address0 = zext_ln69_reg_1355;

assign buffer_c1_5_ce0 = buffer_c1_5_ce0_local;

assign buffer_c1_5_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_5_we0 = buffer_c1_5_we0_local;

assign buffer_c1_6_address0 = zext_ln69_reg_1355;

assign buffer_c1_6_ce0 = buffer_c1_6_ce0_local;

assign buffer_c1_6_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_6_we0 = buffer_c1_6_we0_local;

assign buffer_c1_7_address0 = zext_ln69_reg_1355;

assign buffer_c1_7_ce0 = buffer_c1_7_ce0_local;

assign buffer_c1_7_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_7_we0 = buffer_c1_7_we0_local;

assign buffer_c1_8_address0 = zext_ln69_reg_1355;

assign buffer_c1_8_ce0 = buffer_c1_8_ce0_local;

assign buffer_c1_8_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_8_we0 = buffer_c1_8_we0_local;

assign buffer_c1_9_address0 = zext_ln69_reg_1355;

assign buffer_c1_9_ce0 = buffer_c1_9_ce0_local;

assign buffer_c1_9_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_9_we0 = buffer_c1_9_we0_local;

assign buffer_c1_address0 = zext_ln69_reg_1355;

assign buffer_c1_ce0 = buffer_c1_ce0_local;

assign buffer_c1_d0 = select_ln20_fu_1274_p3;

assign buffer_c1_we0 = buffer_c1_we0_local;

assign conv1_bias_address0 = zext_ln61_fu_1071_p1;

assign conv1_multiplier_address0 = zext_ln61_fu_1071_p1;

assign conv1_shift_address0 = zext_ln61_fu_1071_p1;

assign conv1_weight_address0 = zext_ln74_1_fu_1106_p1;

assign conv1_weight_address1 = zext_ln74_fu_1096_p1;

assign conv1_weight_address2 = zext_ln69_1_fu_1077_p1;

assign conv1_weight_address3 = zext_ln74_2_fu_1052_p1;

assign conv1_weight_address4 = zext_ln74_3_fu_1042_p1;

assign grp_fu_915_p1 = grp_fu_915_p10;

assign grp_fu_915_p10 = conv1_multiplier_load_reg_1534_pp0_iter5_reg;

assign icmp_ln20_fu_1264_p2 = ((tmp_9_fu_1254_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_981_p2 = ((ap_sig_allocacmp_oc_1 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln69_1_fu_961_p2 = ((add_ln66_1 < 8'd90) ? 1'b1 : 1'b0);

assign icmp_ln69_2_fu_967_p2 = ((add_ln66_2 < 7'd90) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_955_p2 = ((add_ln66 < 8'd90) ? 1'b1 : 1'b0);

assign mul_ln74_1_fu_1140_p0 = sext_ln69_4_reg_1404;

assign mul_ln74_2_fu_1145_p0 = sext_ln69_3_reg_1399;

assign p_shl_fu_1023_p3 = {{oc_1_reg_1421}, {2'd0}};

assign res_2_fu_1246_p3 = ((tmp_8_fu_1238_p3[0:0] == 1'b1) ? 13'd0 : trunc_ln13_fu_1234_p1);

assign res_fu_1229_p2 = $signed(acc64_2_reg_1570) >>> zext_ln13_fu_1226_p1;

assign select_ln20_fu_1274_p3 = ((icmp_ln20_reg_1575[0:0] == 1'b1) ? 7'd127 : trunc_ln22_reg_1580);

assign sext_ln63_fu_1156_p1 = $signed(acc_reg_1509);

assign sext_ln69_1_fu_935_p1 = $signed(sext_ln71_4);

assign sext_ln69_2_fu_939_p1 = $signed(sext_ln71_3);

assign sext_ln69_3_fu_947_p1 = $signed(sext_ln71_1);

assign sext_ln69_4_fu_951_p1 = $signed(sext_ln77);

assign sext_ln69_fu_931_p1 = $signed(sext_ln71_5);

assign sext_ln74_2_fu_1159_p1 = $signed(mul_ln74_2_reg_1524);

assign sext_ln74_4_fu_1172_p1 = $signed(add_ln74_5_fu_1166_p2);

assign sext_ln74_5_fu_1176_p1 = grp_fu_1320_p3;

assign sext_ln74_6_fu_1185_p1 = $signed(add_ln74_7_fu_1179_p2);

assign shl_ln10_fu_1211_p2 = 37'd1 << zext_ln10_fu_1208_p1;

assign tmp_8_fu_1238_p3 = res_fu_1229_p2[32'd13];

assign tmp_9_fu_1254_p4 = {{res_2_fu_1246_p3[12:7]}};

assign tmp_reg_1336 = empty;

assign trunc_ln13_fu_1234_p1 = res_fu_1229_p2[12:0];

assign trunc_ln22_fu_1270_p1 = res_2_fu_1246_p3[6:0];

assign trunc_ln61_fu_993_p1 = ap_sig_allocacmp_oc_1[2:0];

assign x_44_fu_1086_p2 = ($signed(sext_ln69_1_reg_1345) + $signed(9'd408));

assign x_45_fu_1057_p2 = ($signed(sext_ln69_reg_1340) + $signed(9'd408));

assign x_fu_1081_p2 = ($signed(sext_ln69_2_reg_1350) + $signed(9'd408));

assign zext_ln10_2_fu_1217_p1 = shl_ln10_fu_1211_p2;

assign zext_ln10_fu_1208_p1 = add_ln10_reg_1565;

assign zext_ln13_fu_1226_p1 = conv1_shift_load_reg_1539_pp0_iter8_reg;

assign zext_ln61_1_fu_1020_p1 = oc_1_reg_1421;

assign zext_ln61_fu_1071_p1 = oc_1_reg_1421_pp0_iter2_reg;

assign zext_ln69_1_fu_1077_p1 = add_ln69_reg_1436_pp0_iter2_reg;

assign zext_ln69_fu_943_p1 = zext_ln60_1;

assign zext_ln74_1_fu_1106_p1 = add_ln74_1_fu_1101_p2;

assign zext_ln74_2_fu_1052_p1 = add_ln74_2_fu_1047_p2;

assign zext_ln74_3_fu_1042_p1 = add_ln74_3_fu_1036_p2;

assign zext_ln74_fu_1096_p1 = add_ln74_fu_1091_p2;

always @ (posedge ap_clk) begin
    zext_ln69_reg_1355[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //tiny_ecg_inference_tiny_ecg_inference_Pipeline_VITIS_LOOP_61_2
