[hls]
relative_roots=D:/ECG-Embedded_System/Wearable_ECG_EdgeAI
# Inferred from syn.array_partition.complete_threshold=4
syn.directive.array_partition=tiny_ecg_inference/fc_bias dim=1 type=complete variable=fc_bias
syn.directive.array_partition=tiny_ecg_inference/fc_multiplier dim=1 type=complete variable=fc_multiplier
syn.directive.array_partition=tiny_ecg_inference/fc_shift dim=1 type=complete variable=fc_shift
# Inferred from performance & pipeline pragmas/directives
syn.directive.array_partition=tiny_ecg_inference/conv1_weight dim=1 type=cyclic factor=5 variable=conv1_weight
syn.directive.array_partition=tiny_ecg_inference/local_ecg dim=1 type=cyclic factor=5 variable=local_ecg
syn.directive.loop_flatten=tiny_ecg_inference/VITIS_LOOP_69_3  
syn.directive.array_partition=tiny_ecg_inference/conv2_weight dim=1 type=cyclic factor=20 variable=conv2_weight
syn.directive.array_partition=tiny_ecg_inference/buffer_c1_0 dim=1 type=cyclic factor=5 variable=buffer_c1_0
syn.directive.loop_flatten=tiny_ecg_inference/VITIS_LOOP_94_6  
syn.directive.array_partition=tiny_ecg_inference/conv3_weight dim=1 type=cyclic factor=24 variable=conv3_weight
syn.directive.array_partition=tiny_ecg_inference/buffer_c2_0 dim=1 type=cyclic factor=3 variable=buffer_c2_0
syn.directive.loop_flatten=tiny_ecg_inference/VITIS_LOOP_122_10  
syn.directive.loop_flatten=tiny_ecg_inference/VITIS_LOOP_147_14  
syn.directive.array_partition=tiny_ecg_inference/fc_weight dim=1 type=complete variable=fc_weight


